knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/xvfb-run /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/xvfb-run /usr/bin/wkhtmltopdf
        options:    []
