version: '2'

services:
  web:
    container_name: php-apache
    build: ./docker/php-apache
    ports:
      - 80:80
    links:
      - db
#      - memcached
    depends_on:
      - db
#      - memcached
#      - mongodb
    volumes:
      - .:/var/www/html
      - ./docker/php-apache/logs:/var/log/apache2
      - ./docker/php-apache/vhosts/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
#    - ./lib/:/usr/share/java/
  
  db:
    build: ./docker/mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: XXXX
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    command: mysqld --sql_mode=""
  
 # mongodb:
 #   image: mongo:3.2.10
 #   container_name: mongodb
 #   ports:
 #     - "27017:27017"
 #   volumes:
 #     - ./mongodb:/var/lib/mongodb
 #   restart: always 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
  
 # memcached:
 #   image: memcached:1.4.33
 #   container_name: memcached
 #   restart: always
 #   ports:
 #    - 11211:11211
 
volumes:
  src:
    driver: local
#  lib:
#    driver: local
  db:
    driver: local
 # mongodb:
 #   driver: local
  
