# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
  path: /
  defaults: { _controller: 'App\Controller\DefaultController::index' }

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"


# app/config/routing.yml
blog:
  path:      /form_company/{id}
  defaults: {_controller: 'App\Controller\CompanyController:companyForm' }

#
#App\Controller\RegistrationController:
#    arguments:
#        $eventDispatcher: '@event_dispatcher'
#            $formFactory: '@fos_user.registration.form.factory'
#            $userManager: '@fos_user.user_manager'
#            $tokenStorage: 'security.token_storage'
#            calls:
#                - method: setContainer
#                  arguments:
#                      - '@service_container'
#            public: true
#
#FOS\UserBundle\Form\Factory\FactoryInterface:
#    alias: 'fos_user.registration.form.factory'
#    public: true


  #dashboard:
  #    path:      /
  #    defaults: {_controller: 'App\Controller\DashboardController:index' }

#ajaxInvoiceBuyRoute:
#    path:    /new_invoice_buy/ajax/test
#    defaults: {_controller: 'App\Controller\IndexInvoiceBuyController:firstAjax' }

