<?php
/**
 * Created by PhpStorm.
 * User: steven
 * Date: 2019-02-05
 * Time: 16:33
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\DateTime;

class CompanyType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
             ->add('socialReason', TextType::class)
             ->add('legalForm',TextType::class)
             ->add('tva',TextType::class)
            ->add('siren',TextType::class)
             ->add('declaration',TextType::class)
             ->add('startDateSocialYear',DateType::class)
             ->add('endDateSocialYear',DateType::class);

    }
}