<?php
/**
 * Created by PhpStorm.
 * User: steven
 * Date: 2019-02-05
 * Time: 16:33
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\DateTime;

class CompanyType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('socialReason', TextType::class,array(
                'required' => true
            ))
            ->add('legalForm', TextType::class,array(
                'required' => true
            ))
            ->add('tva', TextType::class,array(
                'required' => true
            ))
            ->add('adress', TextType::class,array(
                'required' => true
            ))
            ->add('siren', NumberType::class,array(
                'required' => true
            ))
            ->add('postCode', NumberType::class,array(
                'required' => true
            ))
            ->add('mobilephone', TextType::class,array(
                'required' => true
            ))
            ->add('siret', NumberType::class,array(
                'required' => true
            ))
            ->add('city', TextType::class,array(
                'required' => true
            ))
            ->add('country', TextType::class,array(
                'required' => true
            ))
            ->add('declaration', TextType::class,array(
                'required' => true
            ))
            ->add('startDateSocialYear', DateType::class, array(
                'required' => true,
                'widget' => 'single_text',
                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5' => false,

                // adds a class that can be selected in JavaScript
                'attr' => ['class' => 'js-datepicker'],
            ))
            ->add('imageFile', FileType::class,[
                'required' => false,
                'label' => 'Fichier'
            ])

            ->add('endDateSocialYear', DateType::class, array(
                'required' => true,
                'widget' => 'single_text',
                // prevents rendering it as type="date", to avoid HTML5 date pickers
                'html5' => false,
                // adds a class that can be selected in JavaScript
                'attr' => ['class' => 'js-datepicker'],
            ));


    }
}