<?php
/**
 * Created by PhpStorm.
 * User: lahmar
 * Date: 14/04/19
 * Time: 13:18
 */

namespace App\Form;


use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;

class ContactUsType  extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('object', \Symfony\Component\Form\Extension\Core\Type\TextType::class, array('required'=>true))
            ->add('email', EmailType::class, array('required'=>true))
            ->add('message', \Symfony\Component\Form\Extension\Core\Type\TextareaType::class, array('required'=>true));
    }
}