<?php
/**
 * Created by PhpStorm.
 * User: lahmar
 * Date: 01/02/19
 * Time: 16:04
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Length;

class CustomerType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
       // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('lastname', TextType::class)
            ->add('firstname', TextType::class)
            ->add('adress', TextType::class)
            ->add('email', EmailType::class)
            ->add('mobilephone', TelType::class)
            ->add('siren', TextType::class,array(
                'constraints' => [new Length(['max' => 3])]))
            ->add('siret', TextType::class)
            ->add('numtva', TextType::class);
    }
}