<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Length;

class CustomerCompanyType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('personType', ButtonType::class, array(
                'attr' => ['class' => 'btn', 'onclick' => 'Afficher("leschamps")'],

            ))
            ->add('companyname', TextType::class)
            ->add('mobilephone', TelType::class)
            ->add('adress', TextType::class)
            ->add('postcode', NumberType::class)
            ->add('country', TextType::class)
            ->add('email', EmailType::class)
            ->add('siren', TextType::class, array(
                'constraints' => [new Length(['max' => 9])]))
            ->add('siret', TextType::class, array(
                'constraints' => [new Length(['max' => 14])]))
            ->add('numtva', TextType::class);
    }
}