<?php
/**
 * Created by PhpStorm.
 * User: adrienparaiso
 * Date: 06/05/2019
 * Time: 16:26
 */

namespace App\Form;

use App\Entity\Record;
use App\Repository\RecordRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class DevisActionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('article', TextType::class)
            ->add('record', EntityType::class, [
                'class' => Record::class,
                'choice_value' => 'Num',
                'expanded' => false,
                'multiple' => false,
                'query_builder' => function(RecordRepository $er){
                    return $er->getRecords(false);
                }

            ])
            ->add('qtte', IntegerType::class, array(
                'attr' => array(
                    'min' => '0'
                )
            ))
            ->add('prixHT', IntegerType::class)
            ->add('tauxTVA', IntegerType::class, array(
                'attr'=>array(
                    'min'=>'0'
                )
            ))
            ->add('remise', IntegerType::class)
            ->add('montantTTC', IntegerType::class);



    }
}