

INSERT INTO record(Num,Format,Nom) VALUES (1,'abrégé','Comptes de capitaux');
INSERT INTO record(Num,Format,Nom) VALUES (10,'base','Capital et réserves');
INSERT INTO record(Num,Format,Nom) VALUES (101,'abrégé','Capital');
INSERT INTO record(Num,Format,Nom) VALUES (1011,'étendu','Capital souscrit – non appelé');
INSERT INTO record(Num,Format,Nom) VALUES (1012,'étendu','Capital souscrit – appelé, non versé');
INSERT INTO record(Num,Format,Nom) VALUES (1013,'étendu','Capital souscrit – appelé, versé');
INSERT INTO record(Num,Format,Nom) VALUES (10131,'étendu','Capital non amorti');
INSERT INTO record(Num,Format,Nom) VALUES (10132,'étendu','Capital amorti');
INSERT INTO record(Num,Format,Nom) VALUES (1018,'étendu','Capital souscrit soumis à des réglementations particulières');
INSERT INTO record(Num,Format,Nom) VALUES (102,'base','Fonds fiduciaires');
INSERT INTO record(Num,Format,Nom) VALUES (104,'base','Primes liées au capital social');
INSERT INTO record(Num,Format,Nom) VALUES (1041,'étendu','Primes d’émission');
INSERT INTO record(Num,Format,Nom) VALUES (1042,'étendu','Primes de fusion');
INSERT INTO record(Num,Format,Nom) VALUES (1043,'étendu','Primes d’apport');
INSERT INTO record(Num,Format,Nom) VALUES (1044,'étendu','Primes de conversion d’obligations en actions');
INSERT INTO record(Num,Format,Nom) VALUES (1045,'étendu','Bons de souscription d’actions');
INSERT INTO record(Num,Format,Nom) VALUES (105,'abrégé','Écarts de réévaluation');
INSERT INTO record(Num,Format,Nom) VALUES (1051,'étendu','Réserve spéciale de réévaluation');
INSERT INTO record(Num,Format,Nom) VALUES (1052,'étendu','Écart de réévaluation libre');
INSERT INTO record(Num,Format,Nom) VALUES (1053,'étendu','Réserve de réévaluation');
INSERT INTO record(Num,Format,Nom) VALUES (1055,'étendu','Écarts de réévaluation (autres opérations légales)');
INSERT INTO record(Num,Format,Nom) VALUES (1057,'étendu','Autres écarts de réévaluation en France');
INSERT INTO record(Num,Format,Nom) VALUES (1058,'étendu','Autres écarts de réévaluation à l’Étranger');
INSERT INTO record(Num,Format,Nom) VALUES (106,'base','Réserves');
INSERT INTO record(Num,Format,Nom) VALUES (1061,'abrégé','Réserve légale');
INSERT INTO record(Num,Format,Nom) VALUES (10611,'étendu','Réserve légale proprement dite');
INSERT INTO record(Num,Format,Nom) VALUES (10612,'étendu','Plus-values nettes à long terme');
INSERT INTO record(Num,Format,Nom) VALUES (1062,'base','Réserves indisponibles');
INSERT INTO record(Num,Format,Nom) VALUES (1063,'abrégé','Réserves statutaires ou contractuelles');
INSERT INTO record(Num,Format,Nom) VALUES (1064,'abrégé','Réserves réglementées');
INSERT INTO record(Num,Format,Nom) VALUES (10641,'étendu','Plus-values nettes à long terme');
INSERT INTO record(Num,Format,Nom) VALUES (10643,'étendu','Réserves consécutives à l’octroi de subventions d’investissement');
INSERT INTO record(Num,Format,Nom) VALUES (10648,'étendu','Autres réserves réglementées');
INSERT INTO record(Num,Format,Nom) VALUES (1068,'abrégé','Autres réserves');
INSERT INTO record(Num,Format,Nom) VALUES (10681,'étendu','Réserve de propre assureur');
INSERT INTO record(Num,Format,Nom) VALUES (10688,'étendu','Réserves diverses');
INSERT INTO record(Num,Format,Nom) VALUES (107,'base','Écart d’équivalence');
INSERT INTO record(Num,Format,Nom) VALUES (108,'abrégé','Compte de l’exploitant');
INSERT INTO record(Num,Format,Nom) VALUES (109,'base','Actionnaires : Capital souscrit – non appelé');
INSERT INTO record(Num,Format,Nom) VALUES (11,'base','Report à nouveau (solde créditeur ou débiteur)');
INSERT INTO record(Num,Format,Nom) VALUES (110,'étendu','Report à nouveau (solde créditeur)');
INSERT INTO record(Num,Format,Nom) VALUES (119,'étendu','Report à nouveau (solde débiteur)');
INSERT INTO record(Num,Format,Nom) VALUES (12,'abrégé','Résultat de l’exercice (bénéfice ou perte)');
INSERT INTO record(Num,Format,Nom) VALUES (120,'étendu','Résultat de l’exercice (bénéfice)');
INSERT INTO record(Num,Format,Nom) VALUES (129,'étendu','Résultat de l’exercice (perte)');
INSERT INTO record(Num,Format,Nom) VALUES (13,'base','Subventions d’investissement');
INSERT INTO record(Num,Format,Nom) VALUES (131,'base','Subventions d’équipement');
INSERT INTO record(Num,Format,Nom) VALUES (1311,'étendu','État');
INSERT INTO record(Num,Format,Nom) VALUES (1312,'étendu','Régions');
INSERT INTO record(Num,Format,Nom) VALUES (1313,'étendu','Départements');
INSERT INTO record(Num,Format,Nom) VALUES (1314,'étendu','Communes');
INSERT INTO record(Num,Format,Nom) VALUES (1315,'étendu','Collectivités publiques');
INSERT INTO record(Num,Format,Nom) VALUES (1316,'étendu','Entreprises publiques');
INSERT INTO record(Num,Format,Nom) VALUES (1317,'étendu','Entreprises et organismes privés');
INSERT INTO record(Num,Format,Nom) VALUES (1318,'étendu','Autres');
INSERT INTO record(Num,Format,Nom) VALUES (138,'base','Autres subventions d’investissement (même ventilation que celle du compte 131)');
INSERT INTO record(Num,Format,Nom) VALUES (139,'base','Subventions d’investissement inscrites au compte de résultat');
INSERT INTO record(Num,Format,Nom) VALUES (1391,'base','Subventions d’équipement');
INSERT INTO record(Num,Format,Nom) VALUES (13911,'étendu','État');
INSERT INTO record(Num,Format,Nom) VALUES (13912,'étendu','Régions');
INSERT INTO record(Num,Format,Nom) VALUES (13913,'étendu','Départements');
INSERT INTO record(Num,Format,Nom) VALUES (13914,'étendu','Communes');
INSERT INTO record(Num,Format,Nom) VALUES (13915,'étendu','Collectivités publiques');
INSERT INTO record(Num,Format,Nom) VALUES (13916,'étendu','Entreprises publiques');
INSERT INTO record(Num,Format,Nom) VALUES (13917,'étendu','Entreprises et organismes privés');
INSERT INTO record(Num,Format,Nom) VALUES (13918,'étendu','Autres');
INSERT INTO record(Num,Format,Nom) VALUES (1398,'base','Autres subventions d’investissement (même ventilation que celle du compte 1391)');
INSERT INTO record(Num,Format,Nom) VALUES (14,'base','Provisions réglementées');
INSERT INTO record(Num,Format,Nom) VALUES (142,'base','Provisions réglementées relatives aux immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (1423,'étendu','Provisions pour reconstitution des gisements miniers et pétroliers');
INSERT INTO record(Num,Format,Nom) VALUES (1424,'étendu','Provisions pour investissement (participation des salariés)');
INSERT INTO record(Num,Format,Nom) VALUES (143,'base','Provisions réglementées relatives aux stocks');
INSERT INTO record(Num,Format,Nom) VALUES (1431,'étendu','Hausse des prix');
INSERT INTO record(Num,Format,Nom) VALUES (1432,'étendu','Fluctuation des cours');
INSERT INTO record(Num,Format,Nom) VALUES (144,'base','Provisions réglementées relatives aux autres éléments de l’actif');
INSERT INTO record(Num,Format,Nom) VALUES (145,'abrégé','Amortissements dérogatoires');
INSERT INTO record(Num,Format,Nom) VALUES (146,'abrégé','Provision spéciale de réévaluation');
INSERT INTO record(Num,Format,Nom) VALUES (147,'abrégé','Plus-values réinvesties');
INSERT INTO record(Num,Format,Nom) VALUES (148,'abrégé','Autres provisions réglementées');
INSERT INTO record(Num,Format,Nom) VALUES (15,'abrégé','Provisions');
INSERT INTO record(Num,Format,Nom) VALUES (151,'base','Provisions pour risques');
INSERT INTO record(Num,Format,Nom) VALUES (1511,'étendu','Provisions pour litiges');
INSERT INTO record(Num,Format,Nom) VALUES (1512,'étendu','Provisions pour garanties données aux clients');
INSERT INTO record(Num,Format,Nom) VALUES (1513,'étendu','Provisions pour pertes sur marchés à terme');
INSERT INTO record(Num,Format,Nom) VALUES (1514,'étendu','Provisions pour amendes et pénalités');
INSERT INTO record(Num,Format,Nom) VALUES (1515,'étendu','Provisions pour pertes de change');
INSERT INTO record(Num,Format,Nom) VALUES (1516,'étendu','Provisions pour pertes sur contrats');
INSERT INTO record(Num,Format,Nom) VALUES (1518,'étendu','Autres provisions pour risques');
INSERT INTO record(Num,Format,Nom) VALUES (153,'base','Provisions pour pensions et obligations similaires');
INSERT INTO record(Num,Format,Nom) VALUES (154,'base','Provisions pour restructurations');
INSERT INTO record(Num,Format,Nom) VALUES (155,'base','Provisions pour impôts');
INSERT INTO record(Num,Format,Nom) VALUES (156,'base','Provisions pour renouvellement des immobilisations (entreprises concessionnaires)');
INSERT INTO record(Num,Format,Nom) VALUES (157,'base','Provisions pour charges à répartir sur plusieurs exercices');
INSERT INTO record(Num,Format,Nom) VALUES (1572,'étendu','Provisions pour gros entretien ou grandes révisions');
INSERT INTO record(Num,Format,Nom) VALUES (158,'base','Autres provisions pour charges');
INSERT INTO record(Num,Format,Nom) VALUES (1581,'étendu','Provisions pour remises en état');
INSERT INTO record(Num,Format,Nom) VALUES (16,'abrégé','Emprunts et dettes assimilées');
INSERT INTO record(Num,Format,Nom) VALUES (161,'base','Emprunts obligataires convertibles');
INSERT INTO record(Num,Format,Nom) VALUES (162,'base','Obligations représentatives de passifs nets remis en fiducie');
INSERT INTO record(Num,Format,Nom) VALUES (163,'base','Autres emprunts obligataires');
INSERT INTO record(Num,Format,Nom) VALUES (164,'base','Emprunts auprès des établissements de crédit');
INSERT INTO record(Num,Format,Nom) VALUES (165,'base','Dépôts et cautionnements reçus');
INSERT INTO record(Num,Format,Nom) VALUES (1651,'étendu','Dépôts');
INSERT INTO record(Num,Format,Nom) VALUES (1655,'étendu','Cautionnements');
INSERT INTO record(Num,Format,Nom) VALUES (166,'étendu','Participation des salariés aux résultats');
INSERT INTO record(Num,Format,Nom) VALUES (1661,'étendu','Comptes bloqués');
INSERT INTO record(Num,Format,Nom) VALUES (1662,'étendu','Fonds de participation');
INSERT INTO record(Num,Format,Nom) VALUES (167,'base','Emprunts et dettes assortis de conditions particulières');
INSERT INTO record(Num,Format,Nom) VALUES (1671,'base','Émissions de titres participatifs');
INSERT INTO record(Num,Format,Nom) VALUES (1674,'base','Avances conditionnées de l’État');
INSERT INTO record(Num,Format,Nom) VALUES (1675,'base','Emprunts participatifs');
INSERT INTO record(Num,Format,Nom) VALUES (168,'base','Autres emprunts et dettes assimilées');
INSERT INTO record(Num,Format,Nom) VALUES (1681,'étendu','Autres emprunts');
INSERT INTO record(Num,Format,Nom) VALUES (1685,'étendu','Rentes viagères capitalisées');
INSERT INTO record(Num,Format,Nom) VALUES (1687,'étendu','Autres dettes');
INSERT INTO record(Num,Format,Nom) VALUES (1688,'étendu','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (16881,'étendu','sur emprunts obligataires convertibles');
INSERT INTO record(Num,Format,Nom) VALUES (16883,'étendu','sur autres emprunts obligataires');
INSERT INTO record(Num,Format,Nom) VALUES (16884,'étendu','sur emprunts auprès des établissements de crédit');
INSERT INTO record(Num,Format,Nom) VALUES (16885,'étendu','sur dépôts et cautionnements reçus');
INSERT INTO record(Num,Format,Nom) VALUES (16886,'étendu','sur participation des salariés aux résultats');
INSERT INTO record(Num,Format,Nom) VALUES (16887,'étendu','sur emprunts et dettes assortis de conditions particulières');
INSERT INTO record(Num,Format,Nom) VALUES (16888,'étendu','sur autres emprunts et dettes assimilées');
INSERT INTO record(Num,Format,Nom) VALUES (169,'base','Primes de remboursement des obligations');
INSERT INTO record(Num,Format,Nom) VALUES (17,'base','Dettes rattachées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (171,'base','Dettes rattachées à des participations (groupe)');
INSERT INTO record(Num,Format,Nom) VALUES (174,'base','Dettes rattachées à des participations (hors groupe)');
INSERT INTO record(Num,Format,Nom) VALUES (178,'base','Dettes rattachées à des sociétés en participation');
INSERT INTO record(Num,Format,Nom) VALUES (1781,'étendu','Principal');
INSERT INTO record(Num,Format,Nom) VALUES (1788,'étendu','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (18,'base','Comptes de liaison des établissements et sociétés en participation');
INSERT INTO record(Num,Format,Nom) VALUES (181,'étendu','Comptes de liaison des établissements');
INSERT INTO record(Num,Format,Nom) VALUES (186,'étendu','Biens et prestations de services échangés entre établissements (charges)');
INSERT INTO record(Num,Format,Nom) VALUES (187,'étendu','Biens et prestations de services échangés entre établissements (produits)');
INSERT INTO record(Num,Format,Nom) VALUES (188,'étendu','Comptes de liaison des sociétés en participation');
INSERT INTO record(Num,Format,Nom) VALUES (2,'abrégé','Comptes d’immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (20,'abrégé','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (201,'abrégé','Frais d’établissement');
INSERT INTO record(Num,Format,Nom) VALUES (2011,'étendu','Frais de constitution');
INSERT INTO record(Num,Format,Nom) VALUES (2012,'étendu','Frais de premier établissement');
INSERT INTO record(Num,Format,Nom) VALUES (20121,'étendu','Frais de prospection');
INSERT INTO record(Num,Format,Nom) VALUES (20122,'étendu','Frais de publicité');
INSERT INTO record(Num,Format,Nom) VALUES (2013,'étendu','Frais d’augmentation de capital et d’opérations diverses (fusions, scissions, transformations)');
INSERT INTO record(Num,Format,Nom) VALUES (203,'base','Frais de recherche et de développement');
INSERT INTO record(Num,Format,Nom) VALUES (205,'base','Concessions et droits similaires, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires');
INSERT INTO record(Num,Format,Nom) VALUES (206,'abrégé','Droit au bail');
INSERT INTO record(Num,Format,Nom) VALUES (207,'abrégé','Fonds commercial');
INSERT INTO record(Num,Format,Nom) VALUES (208,'abrégé','Autres immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (2081,'base','Mali de fusion sur actifs incorporels');
INSERT INTO record(Num,Format,Nom) VALUES (21,'abrégé','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (211,'base','Terrains');
INSERT INTO record(Num,Format,Nom) VALUES (2111,'base','Terrains nus');
INSERT INTO record(Num,Format,Nom) VALUES (2112,'base','Terrains aménagés');
INSERT INTO record(Num,Format,Nom) VALUES (2113,'base','Sous-sols et sursols');
INSERT INTO record(Num,Format,Nom) VALUES (2114,'base','Terrains de carrières (Tréfonds)');
INSERT INTO record(Num,Format,Nom) VALUES (2115,'base','Terrains bâtis');
INSERT INTO record(Num,Format,Nom) VALUES (21151,'étendu','Ensembles immobiliers industriels (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (21155,'étendu','Ensembles immobiliers administratifs et commerciaux (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (21158,'étendu','Autres ensembles immobiliers');
INSERT INTO record(Num,Format,Nom) VALUES (211581,'étendu','affectés aux opérations professionnelles (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (211588,'étendu','affectés aux opérations non professionnelles (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (2116,'base','Compte d’ordre sur immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (212,'base','Agencements et aménagements de terrains (même ventilation que celle du compte 211)');
INSERT INTO record(Num,Format,Nom) VALUES (213,'base','Constructions');
INSERT INTO record(Num,Format,Nom) VALUES (2131,'base','Bâtiments');
INSERT INTO record(Num,Format,Nom) VALUES (21311,'étendu','Ensembles immobiliers industriels (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (21315,'étendu','Ensembles immobiliers administratifs et commerciaux (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (21318,'étendu','Autres ensembles immobiliers');
INSERT INTO record(Num,Format,Nom) VALUES (213181,'étendu','affectés aux opérations professionnelles (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (213188,'étendu','affectés aux opérations non professionnelles (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (2135,'base','Installations générales – agencements – aménagements des constructions');
INSERT INTO record(Num,Format,Nom) VALUES (21351,'étendu','Ensembles immobiliers industriels (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (21355,'étendu','Ensembles immobiliers administratifs et commerciaux (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (21358,'étendu','Autres ensembles immobiliers');
INSERT INTO record(Num,Format,Nom) VALUES (213581,'étendu','affectés aux opérations professionnelles (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (213588,'étendu','affectés aux opérations non professionnelles (A, B)');
INSERT INTO record(Num,Format,Nom) VALUES (2138,'base','Ouvrages d’infrastructure');
INSERT INTO record(Num,Format,Nom) VALUES (21381,'étendu','Voies de terre');
INSERT INTO record(Num,Format,Nom) VALUES (21382,'étendu','Voies de fer');
INSERT INTO record(Num,Format,Nom) VALUES (21383,'étendu','Voies d’eau');
INSERT INTO record(Num,Format,Nom) VALUES (21384,'étendu','Barrages');
INSERT INTO record(Num,Format,Nom) VALUES (21385,'étendu','Pistes d’aérodromes');
INSERT INTO record(Num,Format,Nom) VALUES (214,'base','Constructions sur sol d’autrui (même ventilation que celle du compte 213)');
INSERT INTO record(Num,Format,Nom) VALUES (215,'base','Installations techniques, matériels et outillage industriels');
INSERT INTO record(Num,Format,Nom) VALUES (2151,'base','Installations complexes spécialisées');
INSERT INTO record(Num,Format,Nom) VALUES (21511,'étendu','sur sol propre');
INSERT INTO record(Num,Format,Nom) VALUES (21514,'étendu','sur sol d’autrui');
INSERT INTO record(Num,Format,Nom) VALUES (2153,'base','Installations à caractère spécifique');
INSERT INTO record(Num,Format,Nom) VALUES (21531,'étendu','sur sol propre');
INSERT INTO record(Num,Format,Nom) VALUES (21534,'étendu','sur sol d’autrui');
INSERT INTO record(Num,Format,Nom) VALUES (2154,'base','Matériel industriel');
INSERT INTO record(Num,Format,Nom) VALUES (2155,'base','Outillage industriel');
INSERT INTO record(Num,Format,Nom) VALUES (2157,'base','Agencements et aménagements du matériel et outillage industriels');
INSERT INTO record(Num,Format,Nom) VALUES (218,'base','Autres immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (2181,'base','Installations générales, agencements, aménagements divers');
INSERT INTO record(Num,Format,Nom) VALUES (2182,'base','Matériel de transport');
INSERT INTO record(Num,Format,Nom) VALUES (2183,'base','Matériel de bureau et matériel informatique');
INSERT INTO record(Num,Format,Nom) VALUES (2184,'base','Mobilier');
INSERT INTO record(Num,Format,Nom) VALUES (2185,'base','Cheptel');
INSERT INTO record(Num,Format,Nom) VALUES (2186,'base','Emballages récupérables');
INSERT INTO record(Num,Format,Nom) VALUES (2187,'base','Mali de fusions sur actifs corporels');
INSERT INTO record(Num,Format,Nom) VALUES (22,'base','Immobilisations mises en concession');
INSERT INTO record(Num,Format,Nom) VALUES (23,'abrégé','Immobilisations en cours');
INSERT INTO record(Num,Format,Nom) VALUES (231,'base','Immobilisations corporelles en cours');
INSERT INTO record(Num,Format,Nom) VALUES (2312,'étendu','Terrains');
INSERT INTO record(Num,Format,Nom) VALUES (2313,'étendu','Constructions');
INSERT INTO record(Num,Format,Nom) VALUES (2315,'étendu','Installations techniques, matériel et outillage industriels');
INSERT INTO record(Num,Format,Nom) VALUES (2318,'étendu','Autres immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (232,'base','Immobilisations incorporelles en cours');
INSERT INTO record(Num,Format,Nom) VALUES (237,'base','Avances et acomptes versés sur immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (238,'base','Avances et acomptes versés sur commandes d’immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (2382,'étendu','Terrains');
INSERT INTO record(Num,Format,Nom) VALUES (2383,'étendu','Constructions');
INSERT INTO record(Num,Format,Nom) VALUES (2385,'étendu','Installations techniques, matériel et outillage industriels');
INSERT INTO record(Num,Format,Nom) VALUES (2388,'base','Autres immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (25,'base','Parts dans des entreprises liées et créances sur des entreprises liées');
INSERT INTO record(Num,Format,Nom) VALUES (26,'base','Participations et créances rattachées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (261,'base','Titres de participation');
INSERT INTO record(Num,Format,Nom) VALUES (2611,'étendu','Actions');
INSERT INTO record(Num,Format,Nom) VALUES (2618,'étendu','Autres titres');
INSERT INTO record(Num,Format,Nom) VALUES (266,'base','Autres formes de participation');
INSERT INTO record(Num,Format,Nom) VALUES (2661,'étendu','Droits représentatifs d’actifs nets remis en fiducie');
INSERT INTO record(Num,Format,Nom) VALUES (267,'base','Créances rattachées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (2671,'étendu','Créances rattachées à des participations (groupe)');
INSERT INTO record(Num,Format,Nom) VALUES (2674,'étendu','Créances rattachées à des participations (hors groupe)');
INSERT INTO record(Num,Format,Nom) VALUES (2675,'étendu','Versements représentatifs d’apports non capitalisés (appel de fonds)');
INSERT INTO record(Num,Format,Nom) VALUES (2676,'étendu','Avances consolidables');
INSERT INTO record(Num,Format,Nom) VALUES (2677,'étendu','Autres créances rattachées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (2678,'étendu','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (268,'base','Créances rattachées à des sociétés en participation');
INSERT INTO record(Num,Format,Nom) VALUES (2681,'étendu','Principal');
INSERT INTO record(Num,Format,Nom) VALUES (2688,'étendu','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (269,'base','Versements restant à effectuer sur titres de participation non libérés');
INSERT INTO record(Num,Format,Nom) VALUES (27,'abrégé','Autres immobilisations financières');
INSERT INTO record(Num,Format,Nom) VALUES (271,'base','Titres immobilisés autres que les titres immobilisés de l’activité de portefeuille (droit de propriété)');
INSERT INTO record(Num,Format,Nom) VALUES (2711,'étendu','Actions');
INSERT INTO record(Num,Format,Nom) VALUES (2718,'étendu','Autres titres');
INSERT INTO record(Num,Format,Nom) VALUES (272,'base','Titres immobilisés (droit de créance)');
INSERT INTO record(Num,Format,Nom) VALUES (2721,'étendu','Obligations');
INSERT INTO record(Num,Format,Nom) VALUES (2722,'étendu','Bons');
INSERT INTO record(Num,Format,Nom) VALUES (273,'base','Titres immobilisés de l’activité de portefeuille');
INSERT INTO record(Num,Format,Nom) VALUES (274,'base','Prêts');
INSERT INTO record(Num,Format,Nom) VALUES (2741,'étendu','Prêts participatifs');
INSERT INTO record(Num,Format,Nom) VALUES (2742,'étendu','Prêts aux associés');
INSERT INTO record(Num,Format,Nom) VALUES (2743,'étendu','Prêts au personnel');
INSERT INTO record(Num,Format,Nom) VALUES (2748,'étendu','Autres prêts');
INSERT INTO record(Num,Format,Nom) VALUES (275,'base','Dépôts et cautionnements versés');
INSERT INTO record(Num,Format,Nom) VALUES (2751,'étendu','Dépôts');
INSERT INTO record(Num,Format,Nom) VALUES (2755,'étendu','Cautionnements');
INSERT INTO record(Num,Format,Nom) VALUES (276,'base','Autres créances immobilisées');
INSERT INTO record(Num,Format,Nom) VALUES (2761,'étendu','Créances diverses');
INSERT INTO record(Num,Format,Nom) VALUES (2768,'étendu','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (27682,'étendu','sur titres immobilisés (droit de créance)');
INSERT INTO record(Num,Format,Nom) VALUES (27684,'étendu','sur prêts');
INSERT INTO record(Num,Format,Nom) VALUES (27685,'étendu','sur dépôts et cautionnements');
INSERT INTO record(Num,Format,Nom) VALUES (27688,'étendu','sur créances diverses');
INSERT INTO record(Num,Format,Nom) VALUES (277,'base','(Actions propres ou parts propres)');
INSERT INTO record(Num,Format,Nom) VALUES (2771,'étendu','Actions propres ou parts propres');
INSERT INTO record(Num,Format,Nom) VALUES (2772,'étendu','Actions propres ou parts propres en voie d’annulation');
INSERT INTO record(Num,Format,Nom) VALUES (278,'base','Mali de fusion sur actifs financiers');
INSERT INTO record(Num,Format,Nom) VALUES (279,'base','Versements restant à effectuer sur titres immobilisés non libérés');
INSERT INTO record(Num,Format,Nom) VALUES (28,'base','Amortissements des immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (280,'abrégé','Amortissements des immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (2801,'base','Frais d’établissement (même ventilation que celle du compte 201)');
INSERT INTO record(Num,Format,Nom) VALUES (2803,'base','Frais de recherche et de développement');
INSERT INTO record(Num,Format,Nom) VALUES (2805,'base','Concessions et droits similaires, brevets, licences, logiciels, droits et valeurs similaires');
INSERT INTO record(Num,Format,Nom) VALUES (2807,'base','Fonds commercial');
INSERT INTO record(Num,Format,Nom) VALUES (2808,'base','Autres immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (28081,'base','Amortissements du mali de fusion sur actifs incorporels');
INSERT INTO record(Num,Format,Nom) VALUES (281,'abrégé','Amortissements des immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (2812,'base','Agencements, aménagements de terrains (même ventilation que celle du compte 212)');
INSERT INTO record(Num,Format,Nom) VALUES (2813,'base','Constructions (même ventilation que celle du compte 213)');
INSERT INTO record(Num,Format,Nom) VALUES (2814,'base','Constructions sur sol d’autrui (même ventilation que celle du compte 214)');
INSERT INTO record(Num,Format,Nom) VALUES (2815,'base','Installations, matériel et outillage industriels (même ventilation que celle du compte 215)');
INSERT INTO record(Num,Format,Nom) VALUES (2818,'base','Autres immobilisations corporelles (même ventilation que celle du compte 218)');
INSERT INTO record(Num,Format,Nom) VALUES (28187,'base','Amortissement du mali de fusion sur actifs corporels');
INSERT INTO record(Num,Format,Nom) VALUES (282,'base','Amortissements des immobilisations mises en concession');
INSERT INTO record(Num,Format,Nom) VALUES (29,'base','Dépréciations des immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (290,'abrégé','Dépréciations des immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (2905,'base','Marques, procédés, droits et valeurs similaires');
INSERT INTO record(Num,Format,Nom) VALUES (2906,'base','Droit au bail');
INSERT INTO record(Num,Format,Nom) VALUES (2907,'base','Fonds commercial');
INSERT INTO record(Num,Format,Nom) VALUES (2908,'base','Autres immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (29081,'base','Dépréciation du mali de fusion sur actifs incorporels');
INSERT INTO record(Num,Format,Nom) VALUES (291,'abrégé','Dépréciations des immobilisations corporelles (même ventilation que celle du compte 21)');
INSERT INTO record(Num,Format,Nom) VALUES (29187,'base','Dépréciation du mali de fusion sur actifs corporels');
INSERT INTO record(Num,Format,Nom) VALUES (292,'base','Dépréciations des immobilisations mises en concession');
INSERT INTO record(Num,Format,Nom) VALUES (293,'base','Dépréciations des immobilisations en cours');
INSERT INTO record(Num,Format,Nom) VALUES (2931,'base','Immobilisations corporelles en cours');
INSERT INTO record(Num,Format,Nom) VALUES (2932,'base','Immobilisations incorporelles en cours');
INSERT INTO record(Num,Format,Nom) VALUES (296,'base','Dépréciations des participations et créances rattachées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (2961,'base','Titres de participation');
INSERT INTO record(Num,Format,Nom) VALUES (2966,'base','Autres formes de participation');
INSERT INTO record(Num,Format,Nom) VALUES (2967,'base','Créances rattachées à des participations (même ventilation que celle du compte 267)');
INSERT INTO record(Num,Format,Nom) VALUES (2968,'base','Créances rattachées à des sociétés en participation (même ventilation que celle du compte 268)');
INSERT INTO record(Num,Format,Nom) VALUES (297,'abrégé','Dépréciations des autres immobilisations financières');
INSERT INTO record(Num,Format,Nom) VALUES (2971,'base','Titres immobilisés autres que les titres immobilisés de l’activité de portefeuille – droit de propriété (même ventilation que celle du compte 271)');
INSERT INTO record(Num,Format,Nom) VALUES (2972,'base','Droit de créance (même ventilation que celle du compte 272)');
INSERT INTO record(Num,Format,Nom) VALUES (2973,'base','Titres immobilisés de l’activité de portefeuille');
INSERT INTO record(Num,Format,Nom) VALUES (2974,'base','Prêts (même ventilation que celle du compte 274)');
INSERT INTO record(Num,Format,Nom) VALUES (2975,'base','Dépôts et cautionnements versés (même ventilation que celle du compte 275)');
INSERT INTO record(Num,Format,Nom) VALUES (2976,'base','Autres créances immobilisées (même ventilation que celle du compte 276)');
INSERT INTO record(Num,Format,Nom) VALUES (29787,'base','Dépréciation du mali de fusion sur actifs financiers');
INSERT INTO record(Num,Format,Nom) VALUES (3,'abrégé','Comptes de stocks et en-cours');
INSERT INTO record(Num,Format,Nom) VALUES (31,'abrégé','Matières premières (et fournitures)');
INSERT INTO record(Num,Format,Nom) VALUES (311,'base','Matières (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (312,'base','Matières (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (317,'base','Fournitures A, B, C,');
INSERT INTO record(Num,Format,Nom) VALUES (32,'abrégé','Autres approvisionnements');
INSERT INTO record(Num,Format,Nom) VALUES (321,'base','Matières consommables');
INSERT INTO record(Num,Format,Nom) VALUES (3211,'étendu','Matières (ou groupe) C');
INSERT INTO record(Num,Format,Nom) VALUES (3212,'étendu','Matières (ou groupe) D');
INSERT INTO record(Num,Format,Nom) VALUES (322,'base','Fournitures consommables');
INSERT INTO record(Num,Format,Nom) VALUES (3221,'étendu','Combustibles');
INSERT INTO record(Num,Format,Nom) VALUES (3222,'étendu','Produits d’entretien');
INSERT INTO record(Num,Format,Nom) VALUES (3223,'étendu','Fournitures d’atelier et d’usine');
INSERT INTO record(Num,Format,Nom) VALUES (3224,'étendu','Fournitures de magasin');
INSERT INTO record(Num,Format,Nom) VALUES (3225,'étendu','Fournitures de bureau');
INSERT INTO record(Num,Format,Nom) VALUES (326,'base','Emballages');
INSERT INTO record(Num,Format,Nom) VALUES (3261,'étendu','Emballages perdus');
INSERT INTO record(Num,Format,Nom) VALUES (3265,'étendu','Emballages récupérables non identifiables');
INSERT INTO record(Num,Format,Nom) VALUES (3267,'étendu','Emballages à usage mixte');
INSERT INTO record(Num,Format,Nom) VALUES (33,'abrégé','En-cours de production de biens');
INSERT INTO record(Num,Format,Nom) VALUES (331,'base','Produits en cours');
INSERT INTO record(Num,Format,Nom) VALUES (3311,'étendu','Produits en cours P 1');
INSERT INTO record(Num,Format,Nom) VALUES (3312,'étendu','Produits en cours P 2');
INSERT INTO record(Num,Format,Nom) VALUES (335,'base','Travaux en cours');
INSERT INTO record(Num,Format,Nom) VALUES (3351,'étendu','Travaux en cours T 1');
INSERT INTO record(Num,Format,Nom) VALUES (3352,'étendu','Travaux en cours T 2');
INSERT INTO record(Num,Format,Nom) VALUES (34,'abrégé','En-cours de production de services');
INSERT INTO record(Num,Format,Nom) VALUES (341,'base','Études en cours');
INSERT INTO record(Num,Format,Nom) VALUES (3411,'étendu','Études en cours E 1');
INSERT INTO record(Num,Format,Nom) VALUES (3412,'étendu','Études en cours E 2');
INSERT INTO record(Num,Format,Nom) VALUES (345,'base','Prestations de services en cours');
INSERT INTO record(Num,Format,Nom) VALUES (3451,'étendu','Prestations de services S 1');
INSERT INTO record(Num,Format,Nom) VALUES (3452,'étendu','Prestations de services S 2');
INSERT INTO record(Num,Format,Nom) VALUES (35,'abrégé','Stocks de produits');
INSERT INTO record(Num,Format,Nom) VALUES (351,'base','Produits intermédiaires');
INSERT INTO record(Num,Format,Nom) VALUES (3511,'étendu','Produits intermédiaires (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (3512,'étendu','Produits intermédiaires (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (355,'base','Produits finis');
INSERT INTO record(Num,Format,Nom) VALUES (3551,'étendu','Produits finis (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (3552,'étendu','Produits finis (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (358,'base','Produits résiduels (ou matières de récupération)');
INSERT INTO record(Num,Format,Nom) VALUES (3581,'étendu','Déchets');
INSERT INTO record(Num,Format,Nom) VALUES (3585,'étendu','Rebuts');
INSERT INTO record(Num,Format,Nom) VALUES (3586,'étendu','Matières de récupération');
INSERT INTO record(Num,Format,Nom) VALUES (36,'base','(compte à ouvrir, le cas échéant, sous l’intitulé "Stocks provenant d’immobilisations")');
INSERT INTO record(Num,Format,Nom) VALUES (37,'abrégé','Stocks de marchandises');
INSERT INTO record(Num,Format,Nom) VALUES (371,'étendu','Marchandises (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (372,'étendu','Marchandises (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (38,'base','(lorsque l’entité tient un inventaire permanent en comptabilité générale, le compte 38 peut être utilisé pour comptabiliser les stocks en voie d’acheminement, mis en dépôt ou donnés en consignation)');
INSERT INTO record(Num,Format,Nom) VALUES (39,'base','Dépréciations des stocks et en-cours');
INSERT INTO record(Num,Format,Nom) VALUES (391,'abrégé','Dépréciations des matières premières (et fournitures)');
INSERT INTO record(Num,Format,Nom) VALUES (3911,'étendu','Matières (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (3912,'étendu','Matières (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (3917,'étendu','Fournitures A, B, C,');
INSERT INTO record(Num,Format,Nom) VALUES (392,'abrégé','Dépréciations des autres approvisionnements');
INSERT INTO record(Num,Format,Nom) VALUES (3921,'étendu','Matières consommables (même ventilation que celle du compte 321)');
INSERT INTO record(Num,Format,Nom) VALUES (3922,'étendu','Fournitures consommables (même ventilation que celle du compte 322)');
INSERT INTO record(Num,Format,Nom) VALUES (3926,'étendu','Emballages (même ventilation que celle du compte 326)');
INSERT INTO record(Num,Format,Nom) VALUES (393,'abrégé','Dépréciations des en-cours de production de biens');
INSERT INTO record(Num,Format,Nom) VALUES (3931,'étendu','Produits en cours (même ventilation que celle du compte 331)');
INSERT INTO record(Num,Format,Nom) VALUES (3935,'étendu','Travaux en cours (même ventilation que celle du compte 335)');
INSERT INTO record(Num,Format,Nom) VALUES (394,'abrégé','Dépréciations des en-cours de production de services');
INSERT INTO record(Num,Format,Nom) VALUES (3941,'étendu','Études en cours (même ventilation que celle du compte 341)');
INSERT INTO record(Num,Format,Nom) VALUES (3945,'étendu','Prestations de services en cours (même ventilation que celle du compte 345)');
INSERT INTO record(Num,Format,Nom) VALUES (395,'abrégé','Dépréciations des stocks de produits');
INSERT INTO record(Num,Format,Nom) VALUES (3951,'étendu','Produits intermédiaires (même ventilation que celle du compte 351)');
INSERT INTO record(Num,Format,Nom) VALUES (3955,'étendu','Produits finis (même ventilation que celle du compte 355)');
INSERT INTO record(Num,Format,Nom) VALUES (397,'abrégé','Dépréciations des stocks de marchandises');
INSERT INTO record(Num,Format,Nom) VALUES (3971,'étendu','Marchandise (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (3972,'étendu','Marchandise (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (4,'abrégé','Comptes de tiers');
INSERT INTO record(Num,Format,Nom) VALUES (40,'base','Fournisseurs et comptes rattachés');
INSERT INTO record(Num,Format,Nom) VALUES (400,'abrégé','Fournisseurs et comptes rattachés');
INSERT INTO record(Num,Format,Nom) VALUES (401,'base','Fournisseurs');
INSERT INTO record(Num,Format,Nom) VALUES (4011,'étendu','Fournisseurs – Achats de biens et prestations de services');
INSERT INTO record(Num,Format,Nom) VALUES (4017,'étendu','Fournisseurs – Retenues de garantie');
INSERT INTO record(Num,Format,Nom) VALUES (403,'base','Fournisseurs – Effets à payer');
INSERT INTO record(Num,Format,Nom) VALUES (404,'base','Fournisseurs d’immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (4041,'étendu','Fournisseurs – Achats d’immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (4047,'étendu','Fournisseurs d’immobilisations – Retenues de garantie');
INSERT INTO record(Num,Format,Nom) VALUES (405,'base','Fournisseurs d’immobilisations – Effets à payer');
INSERT INTO record(Num,Format,Nom) VALUES (408,'base','Fournisseurs – Factures non parvenues');
INSERT INTO record(Num,Format,Nom) VALUES (4081,'étendu','Fournisseurs');
INSERT INTO record(Num,Format,Nom) VALUES (4084,'étendu','Fournisseurs d’immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (4088,'étendu','Fournisseurs – Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (409,'abrégé','Fournisseurs débiteurs');
INSERT INTO record(Num,Format,Nom) VALUES (4091,'base','Fournisseurs – Avances et acomptes versés sur commandes');
INSERT INTO record(Num,Format,Nom) VALUES (4096,'base','Fournisseurs – Créances pour emballages et matériel à rendre');
INSERT INTO record(Num,Format,Nom) VALUES (4097,'base','Fournisseurs – Autres avoirs');
INSERT INTO record(Num,Format,Nom) VALUES (40971,'étendu','Fournisseurs d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (40974,'étendu','Fournisseurs d’immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (4098,'base','Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus');
INSERT INTO record(Num,Format,Nom) VALUES (41,'base','Clients et comptes rattachés');
INSERT INTO record(Num,Format,Nom) VALUES (410,'abrégé','Clients et comptes rattachés');
INSERT INTO record(Num,Format,Nom) VALUES (411,'base','Clients');
INSERT INTO record(Num,Format,Nom) VALUES (4111,'étendu','Clients – Ventes de biens ou de prestations de services');
INSERT INTO record(Num,Format,Nom) VALUES (4117,'étendu','Clients – Retenues de garantie');
INSERT INTO record(Num,Format,Nom) VALUES (413,'base','Clients – Effets à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (416,'base','Clients douteux ou litigieux');
INSERT INTO record(Num,Format,Nom) VALUES (418,'base','Clients – Produits non encore facturés');
INSERT INTO record(Num,Format,Nom) VALUES (4181,'étendu','Clients – Factures à établir');
INSERT INTO record(Num,Format,Nom) VALUES (4188,'étendu','Clients – Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (419,'abrégé','Clients créditeurs');
INSERT INTO record(Num,Format,Nom) VALUES (4191,'base','Clients – Avances et acomptes reçus sur commandes');
INSERT INTO record(Num,Format,Nom) VALUES (4196,'base','Clients – Dettes sur emballages et matériels consignés');
INSERT INTO record(Num,Format,Nom) VALUES (4197,'base','Clients – Autres avoirs');
INSERT INTO record(Num,Format,Nom) VALUES (4198,'base','Rabais, remises, ristournes à accorder et autres avoirs à établir');
INSERT INTO record(Num,Format,Nom) VALUES (42,'base','Personnel et comptes rattachés');
INSERT INTO record(Num,Format,Nom) VALUES (421,'abrégé','Personnel – Rémunérations dues');
INSERT INTO record(Num,Format,Nom) VALUES (422,'base','Comités d’entreprises, d’établissement, …');
INSERT INTO record(Num,Format,Nom) VALUES (424,'base','Participation des salariés aux résultats');
INSERT INTO record(Num,Format,Nom) VALUES (4246,'étendu','Réserve spéciale');
INSERT INTO record(Num,Format,Nom) VALUES (4248,'étendu','Comptes courants');
INSERT INTO record(Num,Format,Nom) VALUES (425,'base','Personnel – Avances et acomptes');
INSERT INTO record(Num,Format,Nom) VALUES (426,'base','Personnel – Dépôts');
INSERT INTO record(Num,Format,Nom) VALUES (427,'base','Personnel – Oppositions');
INSERT INTO record(Num,Format,Nom) VALUES (428,'abrégé','Personnel – Charges à payer et produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (4282,'étendu','Dettes provisionnées pour congés à payer');
INSERT INTO record(Num,Format,Nom) VALUES (4284,'étendu','Dettes provisionnées pour participation des salariés aux résultats');
INSERT INTO record(Num,Format,Nom) VALUES (4286,'étendu','Autres charges à payer');
INSERT INTO record(Num,Format,Nom) VALUES (4287,'étendu','Produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (43,'abrégé','Sécurité sociale et autres organismes sociaux');
INSERT INTO record(Num,Format,Nom) VALUES (431,'base','Sécurité sociale');
INSERT INTO record(Num,Format,Nom) VALUES (437,'base','Autres organismes sociaux');
INSERT INTO record(Num,Format,Nom) VALUES (438,'base','Organismes sociaux – Charges à payer et produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (4382,'étendu','Charges sociales sur congés à payer');
INSERT INTO record(Num,Format,Nom) VALUES (4386,'étendu','Autres charges à payer');
INSERT INTO record(Num,Format,Nom) VALUES (4387,'étendu','Produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (44,'base','État et autres collectivités publiques');
INSERT INTO record(Num,Format,Nom) VALUES (441,'base','État – Subventions à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (4411,'étendu','Subventions d’investissement');
INSERT INTO record(Num,Format,Nom) VALUES (4417,'étendu','Subventions d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (4418,'étendu','Subventions d’équilibre');
INSERT INTO record(Num,Format,Nom) VALUES (4419,'étendu','Avances sur subventions');
INSERT INTO record(Num,Format,Nom) VALUES (442,'base','État – Impôts et taxes recouvrables sur des tiers');
INSERT INTO record(Num,Format,Nom) VALUES (4424,'étendu','Obligataires');
INSERT INTO record(Num,Format,Nom) VALUES (4425,'étendu','Associés');
INSERT INTO record(Num,Format,Nom) VALUES (443,'base','Opérations particulières avec l’État les collectivités publiques, les organismes internationaux');
INSERT INTO record(Num,Format,Nom) VALUES (4431,'base','Créances sur l’État résultant de la suppression de la règle du décalage d’un mois en matière de TVA');
INSERT INTO record(Num,Format,Nom) VALUES (4438,'base','Intérêts courus sur créances figurant au 4431');
INSERT INTO record(Num,Format,Nom) VALUES (444,'abrégé','État – Impôts sur les bénéfices');
INSERT INTO record(Num,Format,Nom) VALUES (445,'abrégé','État – Taxes sur le chiffre d’affaires');
INSERT INTO record(Num,Format,Nom) VALUES (4452,'base','TVA due intracommunautaire');
INSERT INTO record(Num,Format,Nom) VALUES (4455,'base','Taxes sur le chiffre d’affaires à décaisser');
INSERT INTO record(Num,Format,Nom) VALUES (44551,'étendu','TVA à décaisser');
INSERT INTO record(Num,Format,Nom) VALUES (44558,'étendu','Taxes assimilées à la TVA');
INSERT INTO record(Num,Format,Nom) VALUES (4456,'base','Taxes sur le chiffre d’affaires déductibles');
INSERT INTO record(Num,Format,Nom) VALUES (44562,'étendu','TVA sur immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (44563,'étendu','TVA transférée par d’autres entreprises');
INSERT INTO record(Num,Format,Nom) VALUES (44566,'étendu','TVA sur autres biens et services');
INSERT INTO record(Num,Format,Nom) VALUES (44567,'étendu','Crédit de TVA à reporter');
INSERT INTO record(Num,Format,Nom) VALUES (44568,'étendu','Taxes assimilées à la TVA');
INSERT INTO record(Num,Format,Nom) VALUES (4457,'base','Taxes sur le chiffre d’affaires collectées par l’entreprise');
INSERT INTO record(Num,Format,Nom) VALUES (44571,'étendu','TVA collectée');
INSERT INTO record(Num,Format,Nom) VALUES (44578,'étendu','Taxes assimilées à la TVA');
INSERT INTO record(Num,Format,Nom) VALUES (4458,'base','Taxes sur le chiffre d’affaires à régulariser ou en attente');
INSERT INTO record(Num,Format,Nom) VALUES (44581,'étendu','Acomptes – Régime simplifié d’imposition');
INSERT INTO record(Num,Format,Nom) VALUES (44582,'étendu','Acomptes – Régime de forfait');
INSERT INTO record(Num,Format,Nom) VALUES (44583,'étendu','Remboursement de taxes sur le chiffre d’affaires demandé');
INSERT INTO record(Num,Format,Nom) VALUES (44584,'étendu','TVA récupérée d’avance');
INSERT INTO record(Num,Format,Nom) VALUES (44586,'étendu','Taxes sur le chiffre d’affaires sur factures non parvenues');
INSERT INTO record(Num,Format,Nom) VALUES (44587,'étendu','Taxes sur le chiffre d’affaires sur factures à établir');
INSERT INTO record(Num,Format,Nom) VALUES (446,'base','Obligations cautionnées');
INSERT INTO record(Num,Format,Nom) VALUES (447,'abrégé','Autres impôts, taxes et versements assimilés');
INSERT INTO record(Num,Format,Nom) VALUES (448,'base','État – Charges à payer et produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (4482,'étendu','Charges fiscales sur congés à payer');
INSERT INTO record(Num,Format,Nom) VALUES (4486,'étendu','Charges à payer');
INSERT INTO record(Num,Format,Nom) VALUES (4487,'étendu','Produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (449,'base','Quotas d’émission à acquérir');
INSERT INTO record(Num,Format,Nom) VALUES (45,'abrégé','Groupe et associés');
INSERT INTO record(Num,Format,Nom) VALUES (451,'base','Groupe');
INSERT INTO record(Num,Format,Nom) VALUES (455,'abrégé','Associés – Comptes courants');
INSERT INTO record(Num,Format,Nom) VALUES (4551,'étendu','Principal');
INSERT INTO record(Num,Format,Nom) VALUES (4558,'étendu','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (456,'base','Associés – Opérations sur le capital');
INSERT INTO record(Num,Format,Nom) VALUES (4561,'étendu','Associés – Comptes d’apport en société');
INSERT INTO record(Num,Format,Nom) VALUES (45611,'étendu','Apports en nature');
INSERT INTO record(Num,Format,Nom) VALUES (45615,'étendu','Apports en numéraire');
INSERT INTO record(Num,Format,Nom) VALUES (4562,'étendu','Apporteurs – Capital appelé, non versé');
INSERT INTO record(Num,Format,Nom) VALUES (45621,'étendu','Actionnaires – Capital souscrit et appelé, non versé');
INSERT INTO record(Num,Format,Nom) VALUES (45625,'étendu','Associés – Capital appelé, non versé');
INSERT INTO record(Num,Format,Nom) VALUES (4563,'étendu','Associés – Versements reçus sur augmentation de capital');
INSERT INTO record(Num,Format,Nom) VALUES (4564,'étendu','Associés – Versements anticipés');
INSERT INTO record(Num,Format,Nom) VALUES (4566,'étendu','Actionnaires défaillants');
INSERT INTO record(Num,Format,Nom) VALUES (4567,'étendu','Associés – Capital à rembourser');
INSERT INTO record(Num,Format,Nom) VALUES (457,'base','Associés – Dividendes à payer');
INSERT INTO record(Num,Format,Nom) VALUES (458,'base','Associés – Opérations faites en commun et en GIE');
INSERT INTO record(Num,Format,Nom) VALUES (4581,'étendu','Opérations courantes');
INSERT INTO record(Num,Format,Nom) VALUES (4588,'étendu','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (46,'abrégé','Débiteurs divers et créditeurs divers');
INSERT INTO record(Num,Format,Nom) VALUES (462,'étendu','Créances sur cessions d’immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (464,'étendu','Dettes sur acquisitions de valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (465,'étendu','Créances sur cessions de valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (467,'étendu','Autres comptes débiteurs ou créditeurs');
INSERT INTO record(Num,Format,Nom) VALUES (468,'étendu','Divers – Charges à payer et produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (4686,'étendu','Charges à payer');
INSERT INTO record(Num,Format,Nom) VALUES (4687,'étendu','Produits à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (47,'abrégé','Comptes transitoires ou d’attente');
INSERT INTO record(Num,Format,Nom) VALUES (471,'base','Comptes d’attente');
INSERT INTO record(Num,Format,Nom) VALUES (472,'base','Comptes d’attente');
INSERT INTO record(Num,Format,Nom) VALUES (473,'base','Comptes d’attente');
INSERT INTO record(Num,Format,Nom) VALUES (474,'base','Comptes d’attente');
INSERT INTO record(Num,Format,Nom) VALUES (475,'base','Comptes d’attente');
INSERT INTO record(Num,Format,Nom) VALUES (476,'base','Différence de conversion – Actif');
INSERT INTO record(Num,Format,Nom) VALUES (4761,'étendu','Diminution des créances');
INSERT INTO record(Num,Format,Nom) VALUES (4762,'étendu','Augmentation des dettes');
INSERT INTO record(Num,Format,Nom) VALUES (4768,'étendu','Différences compensées par couverture de change');
INSERT INTO record(Num,Format,Nom) VALUES (477,'base','Différences de conversion – Passif');
INSERT INTO record(Num,Format,Nom) VALUES (4771,'étendu','Augmentation des créances');
INSERT INTO record(Num,Format,Nom) VALUES (4772,'étendu','Diminution des dettes');
INSERT INTO record(Num,Format,Nom) VALUES (4778,'étendu','Différences compensées par couverture de change');
INSERT INTO record(Num,Format,Nom) VALUES (478,'base','Autres comptes transitoires');
INSERT INTO record(Num,Format,Nom) VALUES (4786,'base','Différences d’évaluation sur instruments de trésorerie – ACTIF');
INSERT INTO record(Num,Format,Nom) VALUES (4787,'base','Différences d’évaluation sur instruments de trésorerie – PASSIF');
INSERT INTO record(Num,Format,Nom) VALUES (48,'base','Comptes de régularisation');
INSERT INTO record(Num,Format,Nom) VALUES (481,'abrégé','Charges à répartir sur plusieurs exercices');
INSERT INTO record(Num,Format,Nom) VALUES (4816,'étendu','Frais d’émission des emprunts');
INSERT INTO record(Num,Format,Nom) VALUES (486,'abrégé','Charges constatées d’avance');
INSERT INTO record(Num,Format,Nom) VALUES (487,'abrégé','Produits constatés d’avance');
INSERT INTO record(Num,Format,Nom) VALUES (488,'base','Comptes de répartition périodique des charges et des produits');
INSERT INTO record(Num,Format,Nom) VALUES (4886,'étendu','Charges');
INSERT INTO record(Num,Format,Nom) VALUES (4887,'étendu','Produits');
INSERT INTO record(Num,Format,Nom) VALUES (49,'base','Dépréciations des comptes de tiers');
INSERT INTO record(Num,Format,Nom) VALUES (491,'abrégé','Dépréciations des comptes de clients');
INSERT INTO record(Num,Format,Nom) VALUES (495,'base','Dépréciations des comptes du groupe et des associés');
INSERT INTO record(Num,Format,Nom) VALUES (4951,'base','Comptes du groupe');
INSERT INTO record(Num,Format,Nom) VALUES (4955,'base','Comptes courants des associés');
INSERT INTO record(Num,Format,Nom) VALUES (4958,'base','Opérations faites en commun et en GIE');
INSERT INTO record(Num,Format,Nom) VALUES (496,'abrégé','Dépréciations des comptes de débiteurs divers');
INSERT INTO record(Num,Format,Nom) VALUES (4962,'étendu','Créances sur cessions d’immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (4965,'étendu','Créances sur cessions de valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (4967,'étendu','Autres comptes débiteurs');
INSERT INTO record(Num,Format,Nom) VALUES (5,'abrégé','Comptes financiers');
INSERT INTO record(Num,Format,Nom) VALUES (50,'abrégé','Valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (501,'base','Parts dans des entreprises liées');
INSERT INTO record(Num,Format,Nom) VALUES (502,'base','Actions propres');
INSERT INTO record(Num,Format,Nom) VALUES (5021,'étendu','Actions destinées à être attribuées aux employés et affectées à des plans déterminés');
INSERT INTO record(Num,Format,Nom) VALUES (5022,'étendu','Actions disponibles pour être attribuées aux employés ou pour la régularisation des cours de bourse');
INSERT INTO record(Num,Format,Nom) VALUES (503,'base','Actions');
INSERT INTO record(Num,Format,Nom) VALUES (5031,'étendu','Titres cotés');
INSERT INTO record(Num,Format,Nom) VALUES (5035,'étendu','Titres non cotés');
INSERT INTO record(Num,Format,Nom) VALUES (504,'base','Autres titres conférant un droit de propriété');
INSERT INTO record(Num,Format,Nom) VALUES (505,'base','Obligations et bons émis par la société et rachetés par elle');
INSERT INTO record(Num,Format,Nom) VALUES (506,'base','Obligations');
INSERT INTO record(Num,Format,Nom) VALUES (5061,'étendu','Titres cotés');
INSERT INTO record(Num,Format,Nom) VALUES (5065,'étendu','Titres non cotés');
INSERT INTO record(Num,Format,Nom) VALUES (507,'base','Bons du Trésor et bons de caisse à court terme');
INSERT INTO record(Num,Format,Nom) VALUES (508,'base','Autres valeurs mobilières de placement et autres créances assimilées');
INSERT INTO record(Num,Format,Nom) VALUES (5081,'étendu','Autres valeurs mobilières');
INSERT INTO record(Num,Format,Nom) VALUES (5082,'étendu','Bons de souscription');
INSERT INTO record(Num,Format,Nom) VALUES (5088,'étendu','Intérêts courus sur obligations, bons et valeurs assimilés');
INSERT INTO record(Num,Format,Nom) VALUES (509,'base','Versements restant à effectuer sur valeurs mobilières de placement non libérées');
INSERT INTO record(Num,Format,Nom) VALUES (51,'abrégé','Banques, établissements financiers et assimilés');
INSERT INTO record(Num,Format,Nom) VALUES (511,'base','Valeurs à l’encaissement');
INSERT INTO record(Num,Format,Nom) VALUES (5111,'étendu','Coupons échus à l’encaissement');
INSERT INTO record(Num,Format,Nom) VALUES (5112,'étendu','Chèques à encaisser');
INSERT INTO record(Num,Format,Nom) VALUES (5113,'étendu','Effets à l’encaissement');
INSERT INTO record(Num,Format,Nom) VALUES (5114,'étendu','Effets à l’escompte');
INSERT INTO record(Num,Format,Nom) VALUES (512,'base','Banques');
INSERT INTO record(Num,Format,Nom) VALUES (5121,'étendu','Comptes en monnaie nationale');
INSERT INTO record(Num,Format,Nom) VALUES (5124,'étendu','Comptes en devises');
INSERT INTO record(Num,Format,Nom) VALUES (514,'base','Chèques postaux');
INSERT INTO record(Num,Format,Nom) VALUES (515,'base','Caisses');
INSERT INTO record(Num,Format,Nom) VALUES (516,'base','Sociétés de bourse');
INSERT INTO record(Num,Format,Nom) VALUES (517,'base','Autres organismes financiers');
INSERT INTO record(Num,Format,Nom) VALUES (518,'base','Intérêts courus');
INSERT INTO record(Num,Format,Nom) VALUES (5181,'étendu','Intérêts courus à payer');
INSERT INTO record(Num,Format,Nom) VALUES (5188,'étendu','Intérêts courus à recevoir');
INSERT INTO record(Num,Format,Nom) VALUES (519,'base','Concours bancaires courants');
INSERT INTO record(Num,Format,Nom) VALUES (5191,'étendu','Crédit de mobilisation de créances commerciales');
INSERT INTO record(Num,Format,Nom) VALUES (5193,'étendu','Mobilisation de créances nées à l’étranger');
INSERT INTO record(Num,Format,Nom) VALUES (5198,'étendu','Intérêts courus sur concours bancaires courants');
INSERT INTO record(Num,Format,Nom) VALUES (52,'base','Instruments de trésorerie');
INSERT INTO record(Num,Format,Nom) VALUES (53,'abrégé','Caisse');
INSERT INTO record(Num,Format,Nom) VALUES (531,'base','Caisse siège social');
INSERT INTO record(Num,Format,Nom) VALUES (5311,'étendu','Caisse en monnaie nationale');
INSERT INTO record(Num,Format,Nom) VALUES (5314,'étendu','Caisse en devises');
INSERT INTO record(Num,Format,Nom) VALUES (532,'étendu','Caisse succursale (ou usine) A');
INSERT INTO record(Num,Format,Nom) VALUES (533,'étendu','Caisse succursale (ou usine) B');
INSERT INTO record(Num,Format,Nom) VALUES (54,'abrégé','Régies d’avance et accréditifs');
INSERT INTO record(Num,Format,Nom) VALUES (58,'abrégé','Virements internes');
INSERT INTO record(Num,Format,Nom) VALUES (59,'base','Dépréciations des comptes financiers');
INSERT INTO record(Num,Format,Nom) VALUES (590,'abrégé','Dépréciations des valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (5903,'base','Actions');
INSERT INTO record(Num,Format,Nom) VALUES (5904,'base','Autres titres conférant un droit de propriété');
INSERT INTO record(Num,Format,Nom) VALUES (5906,'base','Obligations');
INSERT INTO record(Num,Format,Nom) VALUES (5908,'base','Autres valeurs mobilières de placement et créances assimilées');
INSERT INTO record(Num,Format,Nom) VALUES (6,'abrégé','Comptes de charges');
INSERT INTO record(Num,Format,Nom) VALUES (60,'abrégé','Achats (sauf 603)');
INSERT INTO record(Num,Format,Nom) VALUES (601,'base','Achats stockés – Matières premières (et fournitures)');
INSERT INTO record(Num,Format,Nom) VALUES (6011,'étendu','Matières (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (6012,'étendu','Matières (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (6017,'étendu','Fournitures A, B, C,');
INSERT INTO record(Num,Format,Nom) VALUES (602,'base','Achats stockés – Autres approvisionnements');
INSERT INTO record(Num,Format,Nom) VALUES (6021,'base','Matières consommables');
INSERT INTO record(Num,Format,Nom) VALUES (60211,'étendu','Matières (ou groupe) C');
INSERT INTO record(Num,Format,Nom) VALUES (60212,'étendu','Matières (ou groupe) D');
INSERT INTO record(Num,Format,Nom) VALUES (6022,'base','Fournitures consommables');
INSERT INTO record(Num,Format,Nom) VALUES (60221,'étendu','Combustibles');
INSERT INTO record(Num,Format,Nom) VALUES (60222,'étendu','Produits d’entretien');
INSERT INTO record(Num,Format,Nom) VALUES (60223,'étendu','Fournitures d’atelier et d’usine');
INSERT INTO record(Num,Format,Nom) VALUES (60224,'étendu','Fournitures de magasin');
INSERT INTO record(Num,Format,Nom) VALUES (60225,'étendu','Fourniture de bureau');
INSERT INTO record(Num,Format,Nom) VALUES (6026,'base','Emballages');
INSERT INTO record(Num,Format,Nom) VALUES (60261,'étendu','Emballages perdus');
INSERT INTO record(Num,Format,Nom) VALUES (60265,'étendu','Emballages récupérables non identifiables');
INSERT INTO record(Num,Format,Nom) VALUES (60267,'étendu','Emballages à usage mixte');
INSERT INTO record(Num,Format,Nom) VALUES (604,'base','Achats d’études et prestations de services');
INSERT INTO record(Num,Format,Nom) VALUES (605,'base','Achats de matériel, équipements et travaux');
INSERT INTO record(Num,Format,Nom) VALUES (606,'base','Achats non stockés de matière et fournitures');
INSERT INTO record(Num,Format,Nom) VALUES (6061,'étendu','Fournitures non stockables (eau, énergie, …)');
INSERT INTO record(Num,Format,Nom) VALUES (6063,'étendu','Fournitures d’entretien et de petit équipement');
INSERT INTO record(Num,Format,Nom) VALUES (6064,'étendu','Fournitures administratives');
INSERT INTO record(Num,Format,Nom) VALUES (6068,'étendu','Autres matières et fournitures');
INSERT INTO record(Num,Format,Nom) VALUES (607,'base','Achats de marchandises');
INSERT INTO record(Num,Format,Nom) VALUES (6071,'étendu','Marchandise (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (6072,'étendu','Marchandise (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (608,'base','(Compte réservé, le cas échéant, à la récapitulation des frais accessoires incorporés aux achats)');
INSERT INTO record(Num,Format,Nom) VALUES (609,'base','Rabais, remises et ristournes obtenus sur achats');
INSERT INTO record(Num,Format,Nom) VALUES (6091,'étendu','de matières premières (et fournitures)');
INSERT INTO record(Num,Format,Nom) VALUES (6092,'étendu','d’autres approvisionnements stockés');
INSERT INTO record(Num,Format,Nom) VALUES (6094,'étendu','d’études et prestations de services');
INSERT INTO record(Num,Format,Nom) VALUES (6095,'étendu','de matériel, équipements et travaux');
INSERT INTO record(Num,Format,Nom) VALUES (6096,'étendu','d’approvisionnements non stockés');
INSERT INTO record(Num,Format,Nom) VALUES (6097,'étendu','de marchandises');
INSERT INTO record(Num,Format,Nom) VALUES (6098,'étendu','Rabais, remises et ristournes non affectés');
INSERT INTO record(Num,Format,Nom) VALUES (603,'abrégé','Variations des stocks (approvisionnements et marchandises)');
INSERT INTO record(Num,Format,Nom) VALUES (6031,'base','Variation des stocks de matières premières (et fournitures)');
INSERT INTO record(Num,Format,Nom) VALUES (6032,'base','Variation des stocks des autres approvisionnements');
INSERT INTO record(Num,Format,Nom) VALUES (6037,'base','Variation des stocks de marchandises 61/62 – Autres charges externes');
INSERT INTO record(Num,Format,Nom) VALUES (61,'abrégé','Services extérieurs');
INSERT INTO record(Num,Format,Nom) VALUES (611,'base','Sous-traitance générale');
INSERT INTO record(Num,Format,Nom) VALUES (612,'base','Redevances de crédit-bail');
INSERT INTO record(Num,Format,Nom) VALUES (6122,'base','Crédit-bail mobilier');
INSERT INTO record(Num,Format,Nom) VALUES (6125,'base','Crédit-bail immobilier');
INSERT INTO record(Num,Format,Nom) VALUES (613,'base','Locations');
INSERT INTO record(Num,Format,Nom) VALUES (6132,'étendu','Locations immobilières');
INSERT INTO record(Num,Format,Nom) VALUES (6135,'étendu','Locations mobilières');
INSERT INTO record(Num,Format,Nom) VALUES (6136,'étendu','Malis sur emballages');
INSERT INTO record(Num,Format,Nom) VALUES (614,'base','Charges locatives et de copropriété');
INSERT INTO record(Num,Format,Nom) VALUES (615,'base','Entretien et réparations');
INSERT INTO record(Num,Format,Nom) VALUES (6152,'étendu','sur biens immobiliers');
INSERT INTO record(Num,Format,Nom) VALUES (6155,'étendu','sur biens mobiliers');
INSERT INTO record(Num,Format,Nom) VALUES (6156,'étendu','Maintenance');
INSERT INTO record(Num,Format,Nom) VALUES (616,'base','Primes d’assurances');
INSERT INTO record(Num,Format,Nom) VALUES (6161,'étendu','Multirisques');
INSERT INTO record(Num,Format,Nom) VALUES (6162,'étendu','Assurance obligatoire dommage construction');
INSERT INTO record(Num,Format,Nom) VALUES (6163,'étendu','Assurance – transport');
INSERT INTO record(Num,Format,Nom) VALUES (61636,'étendu','sur achats');
INSERT INTO record(Num,Format,Nom) VALUES (61637,'étendu','sur ventes');
INSERT INTO record(Num,Format,Nom) VALUES (61638,'étendu','sur autres biens');
INSERT INTO record(Num,Format,Nom) VALUES (6164,'étendu','Risques d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (6165,'étendu','Insolvabilité clients');
INSERT INTO record(Num,Format,Nom) VALUES (617,'base','Études et recherches');
INSERT INTO record(Num,Format,Nom) VALUES (618,'base','Divers');
INSERT INTO record(Num,Format,Nom) VALUES (6181,'étendu','Documentation générale');
INSERT INTO record(Num,Format,Nom) VALUES (6183,'étendu','Documentation technique');
INSERT INTO record(Num,Format,Nom) VALUES (6185,'étendu','Frais de colloques, séminaires, conférences');
INSERT INTO record(Num,Format,Nom) VALUES (619,'base','Rabais, remises et ristournes obtenus sur services extérieurs');
INSERT INTO record(Num,Format,Nom) VALUES (62,'abrégé','Autres services extérieurs');
INSERT INTO record(Num,Format,Nom) VALUES (621,'base','Personnel extérieur à l’entreprise');
INSERT INTO record(Num,Format,Nom) VALUES (6211,'étendu','Personnel intérimaire');
INSERT INTO record(Num,Format,Nom) VALUES (6214,'étendu','Personnel détaché ou prêté à l’entreprise');
INSERT INTO record(Num,Format,Nom) VALUES (622,'base','Rémunérations d’intermédiaires et honoraires');
INSERT INTO record(Num,Format,Nom) VALUES (6221,'étendu','Commissions et courtages sur achats');
INSERT INTO record(Num,Format,Nom) VALUES (6222,'étendu','Commissions et courtages sur ventes');
INSERT INTO record(Num,Format,Nom) VALUES (6224,'étendu','Rémunérations des transitaires');
INSERT INTO record(Num,Format,Nom) VALUES (6225,'étendu','Rémunérations d’affacturage');
INSERT INTO record(Num,Format,Nom) VALUES (6226,'étendu','Honoraires');
INSERT INTO record(Num,Format,Nom) VALUES (6227,'étendu','Frais d’actes et de contentieux');
INSERT INTO record(Num,Format,Nom) VALUES (6228,'étendu','Divers');
INSERT INTO record(Num,Format,Nom) VALUES (623,'base','Publicité, publications, relations publiques');
INSERT INTO record(Num,Format,Nom) VALUES (6231,'étendu','Annonces et insertions');
INSERT INTO record(Num,Format,Nom) VALUES (6232,'étendu','Échantillons');
INSERT INTO record(Num,Format,Nom) VALUES (6233,'étendu','Foires et expositions');
INSERT INTO record(Num,Format,Nom) VALUES (6234,'étendu','Cadeaux à la clientèle');
INSERT INTO record(Num,Format,Nom) VALUES (6235,'étendu','Primes');
INSERT INTO record(Num,Format,Nom) VALUES (6236,'étendu','Catalogues et imprimés');
INSERT INTO record(Num,Format,Nom) VALUES (6237,'étendu','Publications');
INSERT INTO record(Num,Format,Nom) VALUES (6238,'étendu','Divers (pourboires, dons courants, …)');
INSERT INTO record(Num,Format,Nom) VALUES (624,'base','Transports de biens et transports collectifs du personnel');
INSERT INTO record(Num,Format,Nom) VALUES (6241,'étendu','Transports sur achats');
INSERT INTO record(Num,Format,Nom) VALUES (6242,'étendu','Transports sur ventes');
INSERT INTO record(Num,Format,Nom) VALUES (6243,'étendu','Transports entre établissements ou chantiers');
INSERT INTO record(Num,Format,Nom) VALUES (6244,'étendu','Transports administratifs');
INSERT INTO record(Num,Format,Nom) VALUES (6247,'étendu','Transports collectifs du personnel');
INSERT INTO record(Num,Format,Nom) VALUES (6248,'étendu','Divers');
INSERT INTO record(Num,Format,Nom) VALUES (625,'base','Déplacements, missions et réceptions');
INSERT INTO record(Num,Format,Nom) VALUES (6251,'étendu','Voyages et déplacements');
INSERT INTO record(Num,Format,Nom) VALUES (6255,'étendu','Frais de déménagement');
INSERT INTO record(Num,Format,Nom) VALUES (6256,'étendu','Missions');
INSERT INTO record(Num,Format,Nom) VALUES (6257,'étendu','Réceptions');
INSERT INTO record(Num,Format,Nom) VALUES (626,'base','Frais postaux et de télécommunications');
INSERT INTO record(Num,Format,Nom) VALUES (627,'base','Services bancaires et assimilés');
INSERT INTO record(Num,Format,Nom) VALUES (6271,'étendu','Frais sur titres (achat, vente, garde)');
INSERT INTO record(Num,Format,Nom) VALUES (6272,'étendu','Commissions et frais sur émission d’emprunts');
INSERT INTO record(Num,Format,Nom) VALUES (6275,'étendu','Frais sur effets');
INSERT INTO record(Num,Format,Nom) VALUES (6276,'étendu','Location de coffres');
INSERT INTO record(Num,Format,Nom) VALUES (6278,'étendu','Autres frais et commissions sur prestations de services');
INSERT INTO record(Num,Format,Nom) VALUES (628,'base','Divers');
INSERT INTO record(Num,Format,Nom) VALUES (6281,'étendu','Concours divers (cotisations, )');
INSERT INTO record(Num,Format,Nom) VALUES (6284,'étendu','Frais de recrutement de personnel');
INSERT INTO record(Num,Format,Nom) VALUES (629,'base','Rabais, remises et ristournes obtenus sur autres services extérieurs');
INSERT INTO record(Num,Format,Nom) VALUES (63,'abrégé','Impôts, taxes et versements assimilés');
INSERT INTO record(Num,Format,Nom) VALUES (631,'base','Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)');
INSERT INTO record(Num,Format,Nom) VALUES (6311,'étendu','Taxe sur les salaires');
INSERT INTO record(Num,Format,Nom) VALUES (6312,'étendu','Taxe d’apprentissage');
INSERT INTO record(Num,Format,Nom) VALUES (6313,'étendu','Participation des employeurs à la formation professionnelle continue');
INSERT INTO record(Num,Format,Nom) VALUES (6314,'étendu','Cotisation pour défaut d’investissement obligatoire dans la construction');
INSERT INTO record(Num,Format,Nom) VALUES (6318,'étendu','Autres');
INSERT INTO record(Num,Format,Nom) VALUES (633,'base','Impôts, taxes et versements assimilés sur rémunérations (autres organismes)');
INSERT INTO record(Num,Format,Nom) VALUES (6331,'étendu','Versement de transport');
INSERT INTO record(Num,Format,Nom) VALUES (6332,'étendu','Allocations logement');
INSERT INTO record(Num,Format,Nom) VALUES (6333,'étendu','Participation des employeurs à la formation professionnelle continue');
INSERT INTO record(Num,Format,Nom) VALUES (6334,'étendu','Participation des employeurs à l’effort de construction');
INSERT INTO record(Num,Format,Nom) VALUES (6335,'étendu','Versements libératoires ouvrant droit à l’exonération de la taxe d’apprentissage');
INSERT INTO record(Num,Format,Nom) VALUES (6338,'étendu','Autres');
INSERT INTO record(Num,Format,Nom) VALUES (635,'base','Autres impôts, taxes et versements assimilés (administrations des impôts)');
INSERT INTO record(Num,Format,Nom) VALUES (6351,'étendu','Impôts directs (sauf impôts sur les bénéfices)');
INSERT INTO record(Num,Format,Nom) VALUES (63511,'étendu','Contribution économique territoriale');
INSERT INTO record(Num,Format,Nom) VALUES (63512,'étendu','Taxes foncières');
INSERT INTO record(Num,Format,Nom) VALUES (63513,'étendu','Autres impôts locaux');
INSERT INTO record(Num,Format,Nom) VALUES (63514,'étendu','Taxe sur les véhicules des sociétés');
INSERT INTO record(Num,Format,Nom) VALUES (6352,'étendu','Taxe sur le chiffre d’affaires non récupérables');
INSERT INTO record(Num,Format,Nom) VALUES (6353,'étendu','Impôts indirects');
INSERT INTO record(Num,Format,Nom) VALUES (6354,'étendu','Droits d’enregistrement et de timbre');
INSERT INTO record(Num,Format,Nom) VALUES (63541,'étendu','Droits de mutation');
INSERT INTO record(Num,Format,Nom) VALUES (6358,'base','Autres droits');
INSERT INTO record(Num,Format,Nom) VALUES (637,'base','Autres impôts, taxes et versements assimilés (autres organismes)');
INSERT INTO record(Num,Format,Nom) VALUES (6371,'étendu','Contribution sociale de solidarité à la charge des sociétés');
INSERT INTO record(Num,Format,Nom) VALUES (6372,'étendu','Taxes perçues par les organismes publics internationaux');
INSERT INTO record(Num,Format,Nom) VALUES (6374,'étendu','Impôts et taxes exigibles à l’Étranger');
INSERT INTO record(Num,Format,Nom) VALUES (6378,'étendu','Taxes diverses');
INSERT INTO record(Num,Format,Nom) VALUES (64,'base','Charges de personnel');
INSERT INTO record(Num,Format,Nom) VALUES (641,'abrégé','Rémunérations du personnel');
INSERT INTO record(Num,Format,Nom) VALUES (6411,'étendu','Salaires, appointements');
INSERT INTO record(Num,Format,Nom) VALUES (6412,'étendu','Congés payés');
INSERT INTO record(Num,Format,Nom) VALUES (6413,'étendu','Primes et gratifications');
INSERT INTO record(Num,Format,Nom) VALUES (6414,'étendu','Indemnités et avantages divers');
INSERT INTO record(Num,Format,Nom) VALUES (6415,'étendu','Supplément familial');
INSERT INTO record(Num,Format,Nom) VALUES (644,'abrégé','Rémunération du travail de l’exploitant');
INSERT INTO record(Num,Format,Nom) VALUES (645,'abrégé','Charges de sécurité sociale et de prévoyance');
INSERT INTO record(Num,Format,Nom) VALUES (6451,'étendu','Cotisations à l’URSSAF');
INSERT INTO record(Num,Format,Nom) VALUES (6452,'étendu','Cotisations aux mutuelles');
INSERT INTO record(Num,Format,Nom) VALUES (6453,'étendu','Cotisations aux caisses de retraites');
INSERT INTO record(Num,Format,Nom) VALUES (6454,'étendu','Cotisations aux ASSEDIC');
INSERT INTO record(Num,Format,Nom) VALUES (6458,'étendu','Cotisations aux autres organismes sociaux');
INSERT INTO record(Num,Format,Nom) VALUES (646,'abrégé','Cotisations sociales personnelles de l’exploitant');
INSERT INTO record(Num,Format,Nom) VALUES (647,'base','Autres charges sociales');
INSERT INTO record(Num,Format,Nom) VALUES (6471,'étendu','Prestations directes');
INSERT INTO record(Num,Format,Nom) VALUES (6472,'étendu','Versements aux comités d’entreprise et d’établissement');
INSERT INTO record(Num,Format,Nom) VALUES (6473,'étendu','Versements aux comités d’hygiène et de sécurité');
INSERT INTO record(Num,Format,Nom) VALUES (6474,'étendu','Versements aux autres œuvres sociales');
INSERT INTO record(Num,Format,Nom) VALUES (6475,'étendu','Médecine du travail, pharmacie');
INSERT INTO record(Num,Format,Nom) VALUES (648,'base','Autres charges de personnel');
INSERT INTO record(Num,Format,Nom) VALUES (65,'abrégé','Autres charges de gestion courante');
INSERT INTO record(Num,Format,Nom) VALUES (651,'base','Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires');
INSERT INTO record(Num,Format,Nom) VALUES (6511,'étendu','Redevances pour concessions, brevets, licences, marques, procédés, logiciels');
INSERT INTO record(Num,Format,Nom) VALUES (6516,'étendu','Droits d’auteur et de reproduction');
INSERT INTO record(Num,Format,Nom) VALUES (6518,'étendu','Autres droits et valeurs similaires');
INSERT INTO record(Num,Format,Nom) VALUES (653,'base','Jetons de présence');
INSERT INTO record(Num,Format,Nom) VALUES (654,'base','Pertes sur créances irrécouvrables');
INSERT INTO record(Num,Format,Nom) VALUES (6541,'étendu','Créances de l’exercice');
INSERT INTO record(Num,Format,Nom) VALUES (6544,'étendu','Créances des exercices antérieurs');
INSERT INTO record(Num,Format,Nom) VALUES (655,'base','Quote-part de résultat sur opérations faites en commun');
INSERT INTO record(Num,Format,Nom) VALUES (6551,'étendu','Quote-part de bénéfice transférée (comptabilité du gérant)');
INSERT INTO record(Num,Format,Nom) VALUES (6555,'étendu','Quote-part de perte supportée (comptabilité des associés non gérants)');
INSERT INTO record(Num,Format,Nom) VALUES (656,'base','Pertes de change sur créances commerciales');
INSERT INTO record(Num,Format,Nom) VALUES (658,'base','Charges diverses de gestion courante');
INSERT INTO record(Num,Format,Nom) VALUES (66,'abrégé','Charges financières');
INSERT INTO record(Num,Format,Nom) VALUES (661,'base','Charges d’intérêts');
INSERT INTO record(Num,Format,Nom) VALUES (6611,'étendu','Intérêts des emprunts et dettes');
INSERT INTO record(Num,Format,Nom) VALUES (66116,'étendu','des emprunts et dettes assimilées');
INSERT INTO record(Num,Format,Nom) VALUES (66117,'étendu','des dettes rattachées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (6612,'étendu','Charges de la fiducie, résultat de la période');
INSERT INTO record(Num,Format,Nom) VALUES (6615,'étendu','Intérêts des comptes courants et des dépôts créditeurs');
INSERT INTO record(Num,Format,Nom) VALUES (6616,'étendu','Intérêts bancaires et sur opérations de financement (escompte,...)');
INSERT INTO record(Num,Format,Nom) VALUES (6617,'étendu','Intérêts des obligations cautionnées');
INSERT INTO record(Num,Format,Nom) VALUES (6618,'étendu','Intérêts des autres dettes');
INSERT INTO record(Num,Format,Nom) VALUES (66181,'étendu','des dettes commerciales');
INSERT INTO record(Num,Format,Nom) VALUES (66188,'étendu','des dettes diverses');
INSERT INTO record(Num,Format,Nom) VALUES (664,'base','Pertes sur créances liées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (665,'base','Escomptes accordés');
INSERT INTO record(Num,Format,Nom) VALUES (666,'base','Pertes de change financières');
INSERT INTO record(Num,Format,Nom) VALUES (667,'base','Charges nettes sur cessions de valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (668,'base','Autres charges financières');
INSERT INTO record(Num,Format,Nom) VALUES (67,'abrégé','Charges exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (671,'base','Charges exceptionnelles sur opérations de gestion');
INSERT INTO record(Num,Format,Nom) VALUES (6711,'étendu','Pénalités sur marchés (et dédits payés sur achats et ventes)');
INSERT INTO record(Num,Format,Nom) VALUES (6712,'étendu','Pénalités, amendes fiscales et pénales');
INSERT INTO record(Num,Format,Nom) VALUES (6713,'étendu','Dons, libéralités');
INSERT INTO record(Num,Format,Nom) VALUES (6714,'étendu','Créances devenues irrécouvrables dans l’exercice');
INSERT INTO record(Num,Format,Nom) VALUES (6715,'étendu','Subventions accordées');
INSERT INTO record(Num,Format,Nom) VALUES (6717,'étendu','Rappel d’impôts (autres qu’impôts sur les bénéfices)');
INSERT INTO record(Num,Format,Nom) VALUES (6718,'étendu','Autres charges exceptionnelles sur opérations de gestion');
INSERT INTO record(Num,Format,Nom) VALUES (672,'base','(Compte à la disposition des entités pour enregistrer, en cours d’exercice, les charges sur exercices antérieurs)');
INSERT INTO record(Num,Format,Nom) VALUES (674,'base','Opérations de constitution ou liquidation des fiducies');
INSERT INTO record(Num,Format,Nom) VALUES (6741,'étendu','Opérations liées à la constitution de fiducie – Transfert des éléments');
INSERT INTO record(Num,Format,Nom) VALUES (6742,'étendu','Opérations liées à la liquidation de la fiducie');
INSERT INTO record(Num,Format,Nom) VALUES (675,'base','Valeurs comptables des éléments d’actif cédés');
INSERT INTO record(Num,Format,Nom) VALUES (6751,'étendu','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (6752,'étendu','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (6756,'étendu','Immobilisations financières');
INSERT INTO record(Num,Format,Nom) VALUES (6758,'étendu','Autres éléments d’actif');
INSERT INTO record(Num,Format,Nom) VALUES (678,'base','Autres charges exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (6781,'étendu','Malis provenant de clauses d’indexation');
INSERT INTO record(Num,Format,Nom) VALUES (6782,'étendu','Lots');
INSERT INTO record(Num,Format,Nom) VALUES (6783,'étendu','Malis provenant du rachat par l’entreprise d’actions et obligations émises par elle-même');
INSERT INTO record(Num,Format,Nom) VALUES (6788,'étendu','Charges exceptionnelles diverses');
INSERT INTO record(Num,Format,Nom) VALUES (68,'base','Dotations aux amortissements, aux dépréciations et aux provisions');
INSERT INTO record(Num,Format,Nom) VALUES (681,'abrégé','Dotations aux amortissements, aux dépréciations et aux provisions – Charges d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (6811,'base','Dotations aux amortissements sur immobilisations incorporelles et corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (68111,'étendu','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (68112,'étendu','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (6812,'base','Dotations aux amortissements des charges d’exploitation à répartir');
INSERT INTO record(Num,Format,Nom) VALUES (6815,'base','Dotations aux provisions d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (6816,'base','Dotations pour dépréciations des immobilisations incorporelles et corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (68161,'étendu','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (68162,'étendu','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (6817,'base','Dotations pour dépréciations des actifs circulants');
INSERT INTO record(Num,Format,Nom) VALUES (68173,'étendu','Stocks et en-cours');
INSERT INTO record(Num,Format,Nom) VALUES (68174,'étendu','Créances');
INSERT INTO record(Num,Format,Nom) VALUES (686,'abrégé','Dotations aux amortissements, aux dépréciations et aux provisions – Charges financières');
INSERT INTO record(Num,Format,Nom) VALUES (6861,'base','Dotations aux amortissements des primes de remboursement des obligations');
INSERT INTO record(Num,Format,Nom) VALUES (6865,'base','Dotations aux provisions financières');
INSERT INTO record(Num,Format,Nom) VALUES (6866,'base','Dotations pour dépréciations des éléments financiers');
INSERT INTO record(Num,Format,Nom) VALUES (68662,'étendu','Immobilisations financières');
INSERT INTO record(Num,Format,Nom) VALUES (68665,'étendu','Valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (6868,'base','Autres dotations');
INSERT INTO record(Num,Format,Nom) VALUES (687,'abrégé','Dotations aux amortissements, aux dépréciations et aux provisions – Charges exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (6871,'base','Dotations aux amortissements exceptionnels des immobilisations');
INSERT INTO record(Num,Format,Nom) VALUES (6872,'base','Dotations aux provisions réglementées (immobilisations)');
INSERT INTO record(Num,Format,Nom) VALUES (68725,'étendu','Amortissements dérogatoires');
INSERT INTO record(Num,Format,Nom) VALUES (6873,'base','Dotations aux provisions réglementées (stocks)');
INSERT INTO record(Num,Format,Nom) VALUES (6874,'base','Dotations aux autres provisions réglementées');
INSERT INTO record(Num,Format,Nom) VALUES (6875,'base','Dotations aux provisions exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (6876,'base','Dotations pour dépréciations exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (69,'base','Participation des salariés – Impôts sur les bénéfices et assimilés');
INSERT INTO record(Num,Format,Nom) VALUES (691,'abrégé','Participation des salariés aux résultats');
INSERT INTO record(Num,Format,Nom) VALUES (695,'abrégé','Impôts sur les bénéfices');
INSERT INTO record(Num,Format,Nom) VALUES (6951,'étendu','Impôts dus en France');
INSERT INTO record(Num,Format,Nom) VALUES (6952,'étendu','Contribution additionnelle à l’impôt sur les bénéfices');
INSERT INTO record(Num,Format,Nom) VALUES (6954,'étendu','Impôts dus à l’étranger');
INSERT INTO record(Num,Format,Nom) VALUES (696,'base','Suppléments d’impôt sur les sociétés liés aux distributions');
INSERT INTO record(Num,Format,Nom) VALUES (698,'base','Intégration fiscale');
INSERT INTO record(Num,Format,Nom) VALUES (6981,'base','Intégration fiscale – Charges');
INSERT INTO record(Num,Format,Nom) VALUES (6989,'base','Intégration fiscale – Produits');
INSERT INTO record(Num,Format,Nom) VALUES (699,'abrégé','Produits – Reports en arrière des déficits');
INSERT INTO record(Num,Format,Nom) VALUES (7,'abrégé','Comptes de produits');
INSERT INTO record(Num,Format,Nom) VALUES (70,'base','Ventes de produits fabriqués, prestations de services, marchandises');
INSERT INTO record(Num,Format,Nom) VALUES (701,'abrégé','Ventes de produits finis');
INSERT INTO record(Num,Format,Nom) VALUES (7011,'étendu','Produits finis (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (7012,'étendu','Produits finis (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (702,'base','Ventes de produits intermédiaires');
INSERT INTO record(Num,Format,Nom) VALUES (703,'base','Ventes de produits résiduels');
INSERT INTO record(Num,Format,Nom) VALUES (704,'base','Travaux');
INSERT INTO record(Num,Format,Nom) VALUES (7041,'base','Travaux de catégorie (ou activité) A');
INSERT INTO record(Num,Format,Nom) VALUES (7042,'base','Travaux de catégorie (ou activité) B');
INSERT INTO record(Num,Format,Nom) VALUES (705,'base','Études');
INSERT INTO record(Num,Format,Nom) VALUES (706,'abrégé','Prestations de services');
INSERT INTO record(Num,Format,Nom) VALUES (707,'abrégé','Ventes de marchandises');
INSERT INTO record(Num,Format,Nom) VALUES (7071,'étendu','Marchandises (ou groupe) A');
INSERT INTO record(Num,Format,Nom) VALUES (7072,'étendu','Marchandises (ou groupe) B');
INSERT INTO record(Num,Format,Nom) VALUES (708,'abrégé','Produits des activités annexes');
INSERT INTO record(Num,Format,Nom) VALUES (7081,'étendu','Produits des services exploités dans l’intérêt du personnel');
INSERT INTO record(Num,Format,Nom) VALUES (7082,'étendu','Commissions et courtages');
INSERT INTO record(Num,Format,Nom) VALUES (7083,'étendu','Locations diverses');
INSERT INTO record(Num,Format,Nom) VALUES (7084,'étendu','Mise à disposition de personnel facturée');
INSERT INTO record(Num,Format,Nom) VALUES (7085,'étendu','Ports et frais accessoires facturés');
INSERT INTO record(Num,Format,Nom) VALUES (7086,'étendu','Bonis sur reprises d’emballages consignés');
INSERT INTO record(Num,Format,Nom) VALUES (7087,'étendu','Bonifications obtenues des clients et primes sur ventes');
INSERT INTO record(Num,Format,Nom) VALUES (7088,'étendu','Autres produits d’activités annexes (cessions d’approvisionnements,)');
INSERT INTO record(Num,Format,Nom) VALUES (709,'abrégé','Rabais, remises et ristournes accordés par l’entreprise');
INSERT INTO record(Num,Format,Nom) VALUES (7091,'étendu','sur ventes de produits finis');
INSERT INTO record(Num,Format,Nom) VALUES (7092,'étendu','sur ventes de produits intermédiaires');
INSERT INTO record(Num,Format,Nom) VALUES (7094,'étendu','sur travaux');
INSERT INTO record(Num,Format,Nom) VALUES (7095,'étendu','sur études');
INSERT INTO record(Num,Format,Nom) VALUES (7096,'étendu','sur prestations de services');
INSERT INTO record(Num,Format,Nom) VALUES (7097,'étendu','sur ventes de marchandises');
INSERT INTO record(Num,Format,Nom) VALUES (7098,'étendu','sur produits des activités annexes');
INSERT INTO record(Num,Format,Nom) VALUES (71,'base','Production stockée (ou déstockage)');
INSERT INTO record(Num,Format,Nom) VALUES (713,'abrégé','Variation des stocks (en-cours de production, produits)');
INSERT INTO record(Num,Format,Nom) VALUES (7133,'base','Variation des en-cours de production de biens');
INSERT INTO record(Num,Format,Nom) VALUES (71331,'étendu','Produits en cours');
INSERT INTO record(Num,Format,Nom) VALUES (71335,'étendu','Travaux en cours');
INSERT INTO record(Num,Format,Nom) VALUES (7134,'base','Variation des en-cours de production de services');
INSERT INTO record(Num,Format,Nom) VALUES (71341,'étendu','Études en cours');
INSERT INTO record(Num,Format,Nom) VALUES (71345,'étendu','Prestations de services en cours');
INSERT INTO record(Num,Format,Nom) VALUES (7135,'base','Variation des stocks de produits');
INSERT INTO record(Num,Format,Nom) VALUES (71351,'étendu','Produits intermédiaires');
INSERT INTO record(Num,Format,Nom) VALUES (71355,'étendu','Produits finis');
INSERT INTO record(Num,Format,Nom) VALUES (71358,'étendu','Produits résiduels');
INSERT INTO record(Num,Format,Nom) VALUES (72,'abrégé','Production immobilisée');
INSERT INTO record(Num,Format,Nom) VALUES (721,'base','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (722,'base','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (74,'abrégé','Subventions d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (75,'abrégé','Autres produits de gestion courante');
INSERT INTO record(Num,Format,Nom) VALUES (751,'base','Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires');
INSERT INTO record(Num,Format,Nom) VALUES (7511,'étendu','Redevances pour concessions, brevets, licences, marques, procédés, logiciels');
INSERT INTO record(Num,Format,Nom) VALUES (7516,'étendu','Droits d’auteur et de reproduction');
INSERT INTO record(Num,Format,Nom) VALUES (7518,'étendu','Autres droits et valeurs similaires');
INSERT INTO record(Num,Format,Nom) VALUES (752,'base','Revenus des immeubles non affectés à des activités professionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (753,'abrégé','Jetons de présence et rémunérations d’administrateurs, gérants,');
INSERT INTO record(Num,Format,Nom) VALUES (754,'abrégé','Ristournes perçues des coopératives (provenant des excédents)');
INSERT INTO record(Num,Format,Nom) VALUES (755,'abrégé','Quote-parts de résultat sur opérations faites en commun');
INSERT INTO record(Num,Format,Nom) VALUES (7551,'étendu','Quote-part de perte transférée (comptabilité du gérant)');
INSERT INTO record(Num,Format,Nom) VALUES (7555,'étendu','Quote-part de bénéfice attribuée (comptabilité des associés non-gérants)');
INSERT INTO record(Num,Format,Nom) VALUES (756,'base','Gains de change sur créances commerciales');
INSERT INTO record(Num,Format,Nom) VALUES (758,'base','Produits divers de gestion courante');
INSERT INTO record(Num,Format,Nom) VALUES (76,'abrégé','Produits financiers');
INSERT INTO record(Num,Format,Nom) VALUES (761,'base','Produits de participations');
INSERT INTO record(Num,Format,Nom) VALUES (7611,'étendu','Revenus des titres de participation');
INSERT INTO record(Num,Format,Nom) VALUES (7612,'étendu','Produits de la fiducie, résultat de la période');
INSERT INTO record(Num,Format,Nom) VALUES (7616,'étendu','Revenus sur autres formes de participation');
INSERT INTO record(Num,Format,Nom) VALUES (7617,'étendu','Revenus des créances rattachées à des participations');
INSERT INTO record(Num,Format,Nom) VALUES (762,'base','Produits des autres immobilisations financières');
INSERT INTO record(Num,Format,Nom) VALUES (7621,'étendu','Revenus des titres immobilisés');
INSERT INTO record(Num,Format,Nom) VALUES (7626,'étendu','Revenus des prêts');
INSERT INTO record(Num,Format,Nom) VALUES (7627,'étendu','Revenus des créances immobilisées');
INSERT INTO record(Num,Format,Nom) VALUES (763,'base','Revenus des autres créances');
INSERT INTO record(Num,Format,Nom) VALUES (7631,'étendu','Revenus des créances commerciales');
INSERT INTO record(Num,Format,Nom) VALUES (7638,'étendu','Revenus des créances diverses');
INSERT INTO record(Num,Format,Nom) VALUES (764,'base','Revenus des valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (765,'base','Escomptes obtenus');
INSERT INTO record(Num,Format,Nom) VALUES (766,'base','Gains de change financiers');
INSERT INTO record(Num,Format,Nom) VALUES (767,'base','Produits nets sur cessions de valeurs mobilières de placement');
INSERT INTO record(Num,Format,Nom) VALUES (768,'base','Autres produits financiers');
INSERT INTO record(Num,Format,Nom) VALUES (77,'abrégé','Produits exceptionnels');
INSERT INTO record(Num,Format,Nom) VALUES (771,'base','Produits exceptionnels sur opérations de gestion');
INSERT INTO record(Num,Format,Nom) VALUES (7711,'étendu','Dédits et pénalités perçus sur achats et sur ventes');
INSERT INTO record(Num,Format,Nom) VALUES (7713,'étendu','Libéralités reçues');
INSERT INTO record(Num,Format,Nom) VALUES (7714,'étendu','Rentrées sur créances amorties');
INSERT INTO record(Num,Format,Nom) VALUES (7715,'étendu','Subventions d’équilibre');
INSERT INTO record(Num,Format,Nom) VALUES (7717,'étendu','Dégrèvements d’impôts autres qu’impôts sur les bénéfices');
INSERT INTO record(Num,Format,Nom) VALUES (7718,'étendu','Autres produits exceptionnels sur opérations de gestion');
INSERT INTO record(Num,Format,Nom) VALUES (772,'base','(Compte à la disposition des entités pour enregistrer, en cours d’exercice, les produits sur exercices antérieurs)');
INSERT INTO record(Num,Format,Nom) VALUES (774,'base','Opérations de constitution ou liquidation des fiducies');
INSERT INTO record(Num,Format,Nom) VALUES (7741,'étendu','Opérations liées à la constitution de fiducie – Transfert des éléments');
INSERT INTO record(Num,Format,Nom) VALUES (7742,'étendu','Opérations liées à la liquidation de la fiducie');
INSERT INTO record(Num,Format,Nom) VALUES (775,'base','Produits des cessions d’éléments d’actif');
INSERT INTO record(Num,Format,Nom) VALUES (7751,'étendu','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (7752,'étendu','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (7756,'étendu','Immobilisations financières');
INSERT INTO record(Num,Format,Nom) VALUES (7758,'étendu','Autres éléments d’actif');
INSERT INTO record(Num,Format,Nom) VALUES (777,'base','Quote-part des subventions d’investissement virée au résultat de l’exercice');
INSERT INTO record(Num,Format,Nom) VALUES (778,'base','Autres produits exceptionnels');
INSERT INTO record(Num,Format,Nom) VALUES (7781,'étendu','Bonis provenant de clauses d’indexation');
INSERT INTO record(Num,Format,Nom) VALUES (7782,'étendu','Lots');
INSERT INTO record(Num,Format,Nom) VALUES (7783,'étendu','Bonis provenant du rachat par l’entreprise d’actions et d’obligations émises par elle-même');
INSERT INTO record(Num,Format,Nom) VALUES (7788,'étendu','Produits exceptionnels divers');
INSERT INTO record(Num,Format,Nom) VALUES (78,'base','Reprises sur amortissements, dépréciations et provisions');
INSERT INTO record(Num,Format,Nom) VALUES (781,'abrégé','Reprises sur amortissements, dépréciations et provisions (à inscrire dans les produits d’exploitation)');
INSERT INTO record(Num,Format,Nom) VALUES (7811,'base','Reprises sur amortissements des immobilisations incorporelles et corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (78111,'étendu','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (78112,'étendu','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (7815,'base','Reprises sur provisions d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (7816,'base','Reprises sur dépréciations des immobilisations incorporelles et corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (78161,'étendu','Immobilisations incorporelles');
INSERT INTO record(Num,Format,Nom) VALUES (78162,'étendu','Immobilisations corporelles');
INSERT INTO record(Num,Format,Nom) VALUES (7817,'base','Reprises sur dépréciations des actifs circulants');
INSERT INTO record(Num,Format,Nom) VALUES (78173,'étendu','Stocks et en-cours');
INSERT INTO record(Num,Format,Nom) VALUES (78174,'étendu','Créances');
INSERT INTO record(Num,Format,Nom) VALUES (786,'abrégé','Reprises sur provisions pour risques et dépréciations (à inscrire dans les produits financiers)');
INSERT INTO record(Num,Format,Nom) VALUES (7865,'base','Reprises sur provisions financières');
INSERT INTO record(Num,Format,Nom) VALUES (7866,'base','Reprises sur dépréciations des éléments financiers');
INSERT INTO record(Num,Format,Nom) VALUES (78662,'étendu','Immobilisations financières');
INSERT INTO record(Num,Format,Nom) VALUES (78665,'étendu','Valeurs mobilières de placements');
INSERT INTO record(Num,Format,Nom) VALUES (787,'abrégé','Reprises sur provisions et dépréciations (à inscrire dans les produits exceptionnels)');
INSERT INTO record(Num,Format,Nom) VALUES (7872,'base','Reprises sur provisions réglementées (immobilisations)');
INSERT INTO record(Num,Format,Nom) VALUES (78725,'étendu','Amortissements dérogatoires');
INSERT INTO record(Num,Format,Nom) VALUES (78726,'étendu','Provision spéciale de réévaluation');
INSERT INTO record(Num,Format,Nom) VALUES (78727,'étendu','Plus-values réinvesties');
INSERT INTO record(Num,Format,Nom) VALUES (7873,'base','Reprises sur provisions réglementées (stocks)');
INSERT INTO record(Num,Format,Nom) VALUES (7874,'base','Reprises sur autres provisions réglementées');
INSERT INTO record(Num,Format,Nom) VALUES (7875,'base','Reprises sur provisions exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (7876,'base','Reprises sur dépréciations exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (79,'abrégé','Transferts de charges');
INSERT INTO record(Num,Format,Nom) VALUES (791,'base','Transferts de charges d’exploitation');
INSERT INTO record(Num,Format,Nom) VALUES (796,'base','Transferts de charges financières');
INSERT INTO record(Num,Format,Nom) VALUES (797,'base','Transferts de charges exceptionnelles');
INSERT INTO record(Num,Format,Nom) VALUES (8,'abrégé','Comptes spéciaux');
INSERT INTO record(Num,Format,Nom) VALUES (80,'base','Engagements');
INSERT INTO record(Num,Format,Nom) VALUES (801,'abrégé','Engagements donnés par l’entité');
INSERT INTO record(Num,Format,Nom) VALUES (8011,'étendu','Avals, cautions, garanties');
INSERT INTO record(Num,Format,Nom) VALUES (8014,'étendu','Effets circulant sous l’endos de l’entité');
INSERT INTO record(Num,Format,Nom) VALUES (8016,'étendu','Redevances crédit-bail restant à courir');
INSERT INTO record(Num,Format,Nom) VALUES (80161,'étendu','Crédit-bail mobilier');
INSERT INTO record(Num,Format,Nom) VALUES (80165,'étendu','Crédit-bail immobilier');
INSERT INTO record(Num,Format,Nom) VALUES (8018,'étendu','Autres engagements donnés');
INSERT INTO record(Num,Format,Nom) VALUES (802,'abrégé','Engagements reçus par l’entité');
INSERT INTO record(Num,Format,Nom) VALUES (8021,'étendu','Avals, cautions, garanties');
INSERT INTO record(Num,Format,Nom) VALUES (8024,'étendu','Créances escomptées non échues');
INSERT INTO record(Num,Format,Nom) VALUES (8026,'étendu','Engagements reçus pour utilisation en crédit-bail');
INSERT INTO record(Num,Format,Nom) VALUES (80261,'étendu','Crédit-bail mobilier');
INSERT INTO record(Num,Format,Nom) VALUES (80265,'étendu','Crédit-bail immobilier');
INSERT INTO record(Num,Format,Nom) VALUES (8028,'étendu','Autres engagements reçus');
INSERT INTO record(Num,Format,Nom) VALUES (809,'abrégé','Contrepartie des engagements');
INSERT INTO record(Num,Format,Nom) VALUES (8091,'étendu','Contrepartie 801');
INSERT INTO record(Num,Format,Nom) VALUES (8092,'étendu','Contrepartie 802');
INSERT INTO record(Num,Format,Nom) VALUES (88,'base','Résultat en instance d’affectation');
INSERT INTO record(Num,Format,Nom) VALUES (89,'base','Bilan');
INSERT INTO record(Num,Format,Nom) VALUES (890,'étendu','Bilan d’ouverture');
INSERT INTO record(Num,Format,Nom) VALUES (891,'étendu','Bilan de clôture');
